### ISSUE TITLE
check box group

### ISSUE THREAD

**Issue by noahphillips** [getgrav/grav-plugin-admin#1012]
Hi

I'd like to use the 'checkboxes'  field to add classes on the front-end.  The grav docs are very clear on how to write the YAML but not clear on weather how to or if we can use this field on the front end.

at the moment I have:

            .copy_styles:
              type: checkboxes
              label: copy styles
              default:
                  audio-text-center: false
                  bolded: false
              options:
                  audio-text-center: audio-text-center
                  bolded: bolded
              use: keys

How do I set this up on the twig side?

**Comment by rhukster** [comment]
You can use it on the frontend:

```
checkboxes:
            label: Checkboxes
            default:
                - option-a
            type: checkboxes
            options:
                option-a: 'Option A'
                option-b: 'Option B'
```

results in:

![2017-03-08 at 4 30 pm](https://cloud.githubusercontent.com/assets/1084697/23728922/819cb4ec-041c-11e7-886d-ee2414d8bddb.jpg)

which in turn is this HTML:

```html
<div class="form-field  ">
    <div class="form-label">
        <label class="inline">
            Checkboxes
        </label>
    </div>
    <div class="form-data" data-grav-field="checkboxes" data-grav-disabled="true" data-grav-default="[&quot;option-a&quot;]" data-grav-keys="false" data-grav-field-name="data[checkboxes]">
        <span class="checkboxes">
            <input type="checkbox" id="checkboxes-option-a" value="option-a" name="data[checkboxes][checkboxes-option-a]" checked="checked">
            <label style="display: inline" for="checkboxes-option-a">
                                    Option A
                            </label>
        </span>
        <span class="checkboxes">
            <input type="checkbox" id="checkboxes-option-b" value="option-b" name="data[checkboxes][checkboxes-option-b]">
            <label style="display: inline" for="checkboxes-option-b">
                                    Option B
                            </label>
        </span>
    </div>
</div>
```
