### ISSUE TITLE
Markdown editor does not insert paragraphs

### ISSUE THREAD

**Issue by tilb** [getgrav/grav-plugin-admin#1019]
Hi all,
For a custom input I want to use the markdown editor. It saves the content, but it does not recognize paragraphs in the text and just puts it all after each other as if it's one big string. The default ‘content’ input does recognize the paragraphs in the text and outputs it in `<p></p>`. This is the yaml I use in my blueprint:
```
header.company_description:
  # type: editor
  type: markdown
  label: Description
  validate:
    type: textarea
```
I tried both `type: editor` – as I read in the [documentation](https://learn.getgrav.org/forms/blueprints/fields-available#the-editor-field) – and `type: markdown` – as it is configured in the [systems default blueprint](https://github.com/getgrav/grav/blob/develop/system/blueprints/pages/default.yaml) (line 30). @rhukster mentioned to add this issue here. I hope it helps in the development :) Here is the [original forumpost](https://getgrav.org/forum#!/general:markdown-editor-does-not-in).
