### ISSUE TITLE
File type field showing escaped HTML markup

### ISSUE THREAD

**Issue by tomzmtl** [getgrav/grav-plugin-admin#1023]
* Grav `1.1.17`
* Admin `1.2.14`

Steps to reproduce:

* Create new theme.
* Create custom blueprint for a page.
* Add a field of type *File*

Issue: the text in the empty file drop zone contains escaped HTML (see screenshot).

![screen shot 2017-03-16 at 1 19 20 pm](https://cloud.githubusercontent.com/assets/1015603/24009837/863eba64-0a4c-11e7-911a-8efbea96732c.png)

Complete blueprint file:

```
title: Terms and Conditions

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab
          title: Content

          fields:
            filetest:
              type: file
              label: PDF File
              destination: 'user/pdf'
              filesize: 5
              accept:
                - .pdf
              validate:
                required: true

            header.documents:
              name: documents
              type: list
              style: vertical
              label: Documents
              fields:
                .text:
                  type: text
                  label: Text
                  validate:
                    required: true
                .file:
                  type: file
                  label: PDF File
                  destination: 'user/pdf'
                  filesize: 5
                  accept:
                    - .pdf
                  validate:
                    required: true

        options:
          type: tab
          title: Options

          fields:
            header.title:
              type: text
              label: Page title
            route:
              type: select
              label: PLUGIN_ADMIN.PARENT
              classes: fancy
              '@data-options': '\Grav\Common\Page\Pages::parents'
              '@data-default': '\Grav\Plugin\admin::route'
              options:
                '/': PLUGIN_ADMIN.DEFAULT_OPTION_ROOT
```
