### ISSUE TITLE
Custom form with file upload does not submit file

### ISSUE THREAD

**Issue by Flibio** [getgrav/grav-plugin-admin#1025]
Hello, I have created a plugin that adds a custom form to the admin panel. The form includes a `file` field type, but whenever I save the form, the file is not submitted.

Here is the blueprint:

```
title: Speaker List
form:
  validation: loose

  fields:
    speaker:
      type: text
      label: Speaker
      validate:
        required: true
    topic:
      type: text
      label: Topic
      validate:
        required: true
    date:
      type: datetime
      label: Date
      validate:
        required: true
    presentation:
      type: file
      label: Presentation
      destination: 'user/data/speakers/presentations'
      multiple: false
      accept:
        - '*'
```
