### ISSUE TITLE
Theme description key in blueprints.yaml doesn't lookup translation

### ISSUE THREAD

**Issue by jmorel** [getgrav/grav-plugin-admin#1029]
In my theme's blueprints.yaml, the `description` key doesn't lookup translations set in languages.yaml (or in languages/fr.yaml, I tried both setup).

Here is the result:
<img width="784" alt="screen shot 2017-03-19 at 12 31 19" src="https://cloud.githubusercontent.com/assets/1270900/24080594/0c158f98-0ca3-11e7-9f88-f614f5e6d56d.png">

blueprints.yaml (the `...` are an ellipsis for multiple other keys)

```yaml
name: Boite A Cycler
version: 0.0.1
description: BOITEACYCLER.THEME_DESCRIPTION
...
```

languages.yaml

```yaml
BOITEACYCLER:
  THEME_DESCRIPTION: "Le thème de l'association Boite à Cycler"
...
```
