### ISSUE TITLE
Translated string cropped

### ISSUE THREAD

**Issue by jmorel** [getgrav/grav-plugin-admin#1030]
Hello,

I ran into a weird bug. Basically, a translated string is being cropped after the first word and get an unexpected quote char at the beginning. I tried using the string for another field's label (I tried both  replacing the reference and replacing the whole string) and got no trouble there so I assume this is not due to the string itself.

<img width="993" alt="screen shot 2017-03-19 at 12 43 04" src="https://cloud.githubusercontent.com/assets/1270900/24080671/a19b5bdc-0ca4-11e7-8fbf-dc5f46481bc8.png">

Here is the relevant part in blueprints.yaml

```yaml
form:
    footer_columns:
      name: columns
      type: list
      label: BOITEACYCLER.FOOTER_COLUMNS.LABEL
      help: BOITEACYCLER.FOOTER_COLUMNS.HELP
      style: vertical
      fields:
        .content:
          name: content
          type: markdown
          label: BOITEACYCLER.FOOTER_COLUMN_CONTENT.LABEL
          help: BOITEACYCLER.FOOTER_COLUMN_CONTENT.HELP
```

And in languages/fr.yaml
```yaml
BOITEACYCLER:
  FOOTER_COLUMNS:
    LABEL: Colonnes du pied de page
    HELP: Il faut au minimum une colonne dans le pied de page, mais il n'y a pas de limite supérieure (bien qu'il soit déconseillé d'en mettre plus de 3)
  FOOTER_COLUMN_CONTENT:
    LABEL: Contenu de la colonne
    HELP: Essayez d'équilibrer la quantité de contenu des colonnes
```
