### ISSUE TITLE
HTML code in FR translation not interpreted

### ISSUE THREAD

**Issue by jmorel** [getgrav/grav-plugin-admin#1031]
Here is the trouble:
<img width="860" alt="screen shot 2017-03-19 at 13 33 23" src="https://cloud.githubusercontent.com/assets/1270900/24080911/caef0a70-0ca8-11e7-8d17-1bfe5f6c94c0.png">

And the matching code in blueprints.yaml:
```yaml
form:
  fields:
    background:
        type: file
        label: BOITEACYCLER.BACKGROUND.LABEL
        help: BOITEACYCLER.BACKGROUND.HELP
        destination: '@self'
        accept:
            - image/*
        multiple: false
```
