### ISSUE TITLE
Chrome : Unable to click on list-encapsulated markdown editor fields

### ISSUE THREAD

**Issue by parcand** [getgrav/grav-plugin-admin#1037]
List-encapsulated markdown editor fields are not responding to mouse clicks in Chrome.

![capture d ecran 2017-03-23 a 10 54 51](https://cloud.githubusercontent.com/assets/22176950/24254028/3df042de-0fb8-11e7-8156-2cc0661b17c0.png)

**Comment by carlu93** [comment]
I can confirm this happening on Windows 10 with Chrome 59 dev. Right clicking in the text will move the cursor to the desired place. Left clicking and dragging is not working.

**Comment by teroyks** [comment]
I have the same issue (latest Grav, macOS Sierra, Chrome 57.0.

Works fine on latest Safari.

**Comment by lukepolak** [comment]
Same here.

You can get into editor by clicking on any toolbar buttons or by tabbing from previous field in list, so that's workaround for me for now. Also, sometimes contents of those editor fields are not shown when you enter to edit that page.

Any idea what could cause this?

**Comment by flaviocopes** [comment]
This is surely a regression, as I'm sure it worked before. Need to find out the commit that introduced the problem, on it.

**Comment by flaviocopes** [comment]
@w00fz I tracked this down to the sortablejs library bump in composer.json in https://github.com/getgrav/grav-plugin-admin/commit/49a9c43d4b42875f05c11c763a11154cf967f61f. 

Setting it to  `"sortablejs": "1.4.2"` (instead of ^1.5.1) and rebuilding the js, works fine again. 

Could not find a changelog for that lib, will need to git-bisect (quite a few commits since 1.4.2) until I find what is the issue. 
In the meantime @rhukster I pushed an updated vendor lib so if we want to release, it will fix the problem.

**Comment by w00fz** [comment]
Might be a setting that needs enabling.

**Comment by honzabilek4** [comment]
Hi,
this is still relevant even after the latest admin plugin update to version 1.6.0.
- Left click doesn't move the cursor, right click works.
- Tested in various browsers (Firefox, Safari, Edge..) however, it affects only Chrome (both Win/macOS versions)

Can we please reopen this issue?

**Comment by rhukster** [comment]
Grrr.. thought this was sorted

**Comment by w00fz** [comment]
What is the Chrome version you are using @honzabilek4 ? I did see this issue myself but after I upgraded Chrome it seems to be working fine again.
I'm running Version 61.0.3163.100 (Official Build) (64-bit).

Can you check your version? And if it's still an issue could you please paste a yaml sample for me to use? As of right now I can't reproduce this issue anymore.

**Comment by honzabilek4** [comment]
Hi,
I've got the exact same version of Chrome right now. 
The very minimal yaml snippet having this issue would be:
```yaml
title: Home
'@extends':
    type: default
    context: blueprints://pages
form:
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        content:
          @unset: true          
        customTab:
          type: tab
          title: Custom Tab
          @ordering: -3
          fields:
            header.persons:
              type: list
              title: Markdown list
              collapsed: false
              style: vertical
              btnLabel: Add Item
              fields:
                .description:
                  type: markdown
                  label: Text
```
