### ISSUE TITLE
Custom add page options

### ISSUE THREAD

**Issue by jwillp** [getgrav/grav-plugin-admin#1066]
As I explained in getgrav/grav#421, it would be great to have the possibility to add custom page types based on blueprints in the Add Page Menu.

For example the menu by default has these choices:
- Add Page
- Add Folder
- Add Modular
I'd like to be able to add thins like:
Add Blog Post
Add Gallery
Add Other special page type.

These options would automatically set things up so that a page for example would be created inside the blog/ directory with an "Item" page template in order to create a blog post etc..

This would be a very useful feature, especially when handing the site to clients who would not have to worry about page templates and folder structure.

**Comment by fireraccoon** [comment]
I would need this soon for a client
do you have any indications on how I could implement this myself?

**Comment by ricardo118** [comment]
Well when you tell a client to add a page, all they gotta do is select a Template for the right thing. If you set up the blog, the gallery, etc it will be just as easy. However, if you really wanted to add buttons, just duplicate the add page button but put the field template preselected and hidden (if you so wish)

**Comment by fireraccoon** [comment]
@ricardo118 I wish i could simply tell them to select the right template and the right folder, unfortunately because of the way the modal is currently designed, the selection box of the folder lists all the pages of the site, which is problematic because in order to find the right folder they need to scroll through potentially hundreds of pages. Hence the predefined modals.

I was hoping for a more elegant solution to implement this than simply copy & pasting the modals, and directly editing the plugin's files. (Because of updates)
I did try to do it though, but I run into problems when trying to specify the default value of select boxes: Strangely enough I never get the right option by default.

Is there any way to extend the admin plugin without changing its code to do what I want ?

**Comment by david-szabo97** [comment]
I think we could make a configuration for this.
I have this in my local version if we can agree on the configuration structure I can refactor it into a PR.

By default, it uses the template used by Add Page.

admin.yaml
```yaml
add_modals:
  post:
    label: Add Post
    blueprint: admin/pages/new_post
    template: custom_template
    link_classes: some_class
    modal_classes: some_modal_class
    with:
      some_data: for the template
    show_in: dropdown
  image:
    label: Add Image
    blueprint: admin/pages/new_image
    show_in: bar
```

An example blueprint. On my blog I have more than 1 authors so with the getNewPostRoute I can generate a route for the user, for example for my account it generates: "/dave/posts"

new_post.yaml
```yaml
form:
  validation: loose
  fields:
    section:
        type: section
        title: Add Post

    title:
      type: text
      label: Post Title
      validate:
        required: true

    folder:
      type: hidden

    route:
      type: hidden
      data-default@: '\Grav\Plugin\MyPlugin::getNewPostRoute'

    name:
      type: hidden
      default: 'post'

    visible:
      type: hidden
      default: ''

    blueprint:
      type: blueprint
```

Some images

![screenshot from 2017-04-26 11-45-05](https://cloud.githubusercontent.com/assets/2256104/25428365/ea116a20-2a75-11e7-8841-63124609201b.png)
![screenshot from 2017-04-26 11-45-26](https://cloud.githubusercontent.com/assets/2256104/25428364/ea110fee-2a75-11e7-9dd4-17ddaca76bf6.png)
