### ISSUE TITLE
Problem with showing images on list

### ISSUE THREAD

**Issue by fourroses666** [getgrav/grav-plugin-admin#1075]
I have an onepage site. The manager works fine, but showing the uploaded images on the front page gives an error.

My onepage.yaml  (see .afb)

```
        tab3:
          type: tab
          title: Diensten

          fields:
            header.diensten:
              name: diensten
              type: list
              label: Diensten blokken
              style: vertical

              fields:
                .kop:
                  label: Kop
                  type: text
                .afb:
                  label: Afbeelding
                  type: file
                  destination: 'self@'
                  multiple: false
                  accept:
                    - image/*
```
So I have the option to upload an image:
![list](https://cloud.githubusercontent.com/assets/523389/25185124/bc1c0eda-251c-11e7-8f89-912ce3d0508e.jpg)

This all works fine.

Then in my onepage.html.twig

```
        <div class="d-blokken respons">

            {% for diensten in page.header.diensten %}

                <div class="item">
                  <img src="{{ diensten.afb }}" alt="" />
                  <h4>{{ diensten.kop }}</h4>
                </div>

            {% endfor %}
     

          <div class="clear"></div>
        </div>
```

The {{ diensten.kop }} works great.
It seems `{{ diensten.afb }}` gives an error. 

`"An exception has been thrown during the rendering of a template ("Array to string conversion")."`

Do I need to add .media or some other way to "call"  the image?

Just started experimenting with Grav. Does it need a partial?! Really have no idea.
