### ISSUE TITLE
Content (esp. line breaks) in YAML frontmatter

### ISSUE THREAD

**Issue by lguariento** [getgrav/grav-plugin-admin#1095]
Hello,

in a situation where my blueprint is:

```
title: info
'@extends':
    type: default
    context: blueprints://pages
form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab

          fields:

            header.tabs:
              type: list
              label: Add a tab
              fields:
                .content:
                  type: markdown
                  label: Content of tab
                .title:
                  type: text
                  label: Title
```

when I input some text with line breaks (or ") it get rendered just fine in the editor (simple mode) and in the front end of the website (with the |markdown pipe). Nevertheless it gets saved with lots of \n\r  etc. in the .md file.
