### ISSUE TITLE
ReferenceError: jQuery is not defined – vendor.min.js:1:872

### ISSUE THREAD

**Issue by adrian5** [getgrav/grav-plugin-admin#1140]
Since it's very difficult to get Grav related help, I thought I'd ask here, even if the problem is likely on me, rather than a bug.

I noticed that the Admin Plugin doesn't allow me to scroll anymore and that a few Dashboard widgets are stuck loading. Opening the console, I found above message about jQuery.

I recently added new assets to `/user/config/system.yaml`, so it might have something to do with that. I now have it looking like this again:

```
assets:
  css_pipeline: false
  css_pipeline_include_externals: false
  css_pipeline_before_excludes: false
  css_minify: false
  css_minify_windows: false
  css_rewrite: false
  js_pipeline: true
  js_pipeline_include_externals: false
  js_pipeline_before_excludes: false
  js_minify: false
  enable_asset_timestamp: true
  collections:
    jquery: system://assets/jquery/jquery-2.1.3.min.js
```

Any suggestions welcome.
