### ISSUE TITLE
Editor field's tooltip is broken

### ISSUE THREAD

**Issue by tranduyhung** [getgrav/grav-plugin-admin#1179]
To reproduce this problem, create default.yaml in user/themes/antimatter/blueprints folder

````
title: Test
'@extends':
    type: default
    context: blueprints://pages


form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab

          fields:
            header.a:
              type: textarea
              label: This is a
              help: This is a test field
            header.b:
              type: editor
              label: This is b
              help: This is a test field
````

Go to Admin and edit any page which uses `default` template. Hover mouse pointer on `This is b` label to see the tooltip, it is `"This` instead of `This is a test field`.

It seems this problem only happens with `editor` field.

Grav v1.3.1 - Admin v1.5.1 
Tested and confirmed on Chrome and Firefox
