### ISSUE TITLE
[Suggestion]  add custom attribute to text field for instance

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav-plugin-admin#1187]
For example in text field `text.html.twig`
````
{% block input_attributes %}
  {% for attribute in field.attributes %}
      {{attribute.name}}="{{attribute.value}}"
  {% endfor %}
    type="text"
    {{ parent() }}
{% endblock %}
````
and in your form
something like this
````
            name: phone
            id: phone
            classes: my-class
            outerclasses: my-outerclass
            label: Mylabel
            placeholder: 'Placeholder label'
            type: text
            attributes:
                 -
                   name: my-custom-attr
                   value: my-value
````
it will render like this
`<input name="data[phone]" value="" my-custom-attr="my-value" type="text" class="my-class" id="phone" placeholder="Placeholder label">`
