### ISSUE TITLE
replace-default@ not working?

### ISSUE THREAD

**Issue by mncrff** [getgrav/grav-plugin-admin#1192]
Here is the YAML in my parent blueprint for the field in question:
```
header.visibility:
    type: toggle
    highlight: 1
    options:
        1: 'show'
        0: 'hide'
    default: 1
    validate:
        type: bool
```

And now in my inheriting blueprint:
```
    header.visibility:
        replace-options@: true
        options:
            1: 'test'
            0: 'hide'
        replace-default@: true
            default: 0
```

I am able to replace the options just fine, but for some reason I cannot get the default to change using `replace-default@`. I also tried using the alias `unset-default@` also without success. The documentation states 'You can do the same for individual properties', so does/should this apply to all properties?

**Comment by rhukster** [comment]
@mahagr you mind looking at this?

**Comment by mahagr** [comment]
IMHO there's no need to use `replace-default@` at all as the value isn't an array. Also, YAML is wrong, the meaning of:

```
replace-default@: true
    default: 0
```

is this:

```
replace-default@: 
    - true
    - [default: 0]
```

**Comment by mncrff** [comment]
Sorry I am just getting back this, I had to move along on my project with a less than ideal work-around but wanted to touch base again as this still seems to be an issue when I test it out. I have tried the above YAML formatting in my inheriting template, tried creating a new modular using the template, and I am still seeing an issue here.

![screen shot 2017-08-29 at 11 05 27 am](https://user-images.githubusercontent.com/1697331/29836491-415b4a62-8caa-11e7-9bf8-ed3ad1a972a8.png)

This is the form toggle I'm seeing, which I would expect to be toggle to the falsey 'hide' position. The header.visibility does not seem to be set in the front matter (not sure if it should be) and my element I'm showing/hiding in my twig template by checking this boolean value is showing up (value is truthy).

Have you all tested this on your end? Maybe I am missing something?

**Comment by mahagr** [comment]
I meant that your YAML was wrong and so was mine (which displayed the wrong syntax).

It should look like this:

```yaml
    header.visibility:
        replace-options@: true
        options:
            1: 'test'
            0: 'hide'
        replace-default@: true
        default: 0
```
