### ISSUE TITLE
Attempts to save top level pages with custom blueprints end up failing

### ISSUE THREAD

**Issue by elisiondan** [getgrav/grav-plugin-admin#1194]
Hi,

I stumbled upon an issue when I tried to fully customize the apperance of my blueprint forms. Therefore, I didn't extend the default type, but rather made my own. It threw the following error:

![error](https://user-images.githubusercontent.com/18164307/29217784-03f92a0e-7eb3-11e7-9a07-133ac971e36e.PNG)

I stripped the form a single tab and field and found out that it occured only when i did not extend the default type. So the following doesn't work.

```
title: Drugstore

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:

        openingHours:
            type: tab
            title: Opening hours

            fields:
              header.openingHours:
                type: array
                label: Opening Hours
```

Interestingly enough, this doesn't work only when I attempt to save a page that is at the top level. However, if it is a child page, it works without any problem. 

![problem](https://user-images.githubusercontent.com/18164307/29218043-d28aef9c-7eb3-11e7-92cb-bbd079d0b735.PNG)

I hoped I could temporarily solve it by adding `@extends` and then unsetting all the tabs i didn't want. But it throws the same error (if I remove all three, not if I only remove one or two).

```


        content:
          unset@: true

        advanced:
          unset@: true

        options:
          unset@: true
```

I tested this on a clean installation of grav with admin. The only file I modified is default.yaml and added two pages.

**Comment by rhukster** [comment]
Try adding this in your blueprint:

```
                    route:
                      type: parents
                      label: PLUGIN_ADMIN.PARENT
                      classes: fancy
```

Pretty sure this is required.
