### ISSUE TITLE
fieldset inside list field doesn't save

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav-plugin-admin#1225]
It seems `fieldset` inside `list` field doesn't save data
maybe related to https://github.com/getgrav/grav-plugin-form/issues/189

this is my test yaml

```yaml
header.gridstack_items:
    name: items
    type: list
    label: THEME_DIM_ITEMS
    help: THEME_DIM_ITEMS_HELP
    fields:
      .column_content:
        type: fieldset
        title: THEME_DIM_COLUMNS
        help: THEME_DIM_CONTENT_COLUMNS_HELP
        info: THEME_DIM_CONTENT_COLUMNS_INFO
        text: THEME_DIM_CONTENT_COLUMNS_TEXT
        icon: th
        collapsed: true     # Initial state of fieldset (see collapsible option)
        collapsible: true    # Whether one can expand the fieldset or not
        fields:
          .column_small:
             type: select
             label: THEME_DIM_PHONE_SMARTPHONE
             description: THEME_DIM_PHONE_SMARTPHONE_DESCRIPTION
             options:
                '1': THEME_DIM_ONE
                '2': THEME_DIM_TWO
                '3': THEME_DIM_THREE
                '4': THEME_DIM_FOUR
          .column_medium:
             type: select
             label: THEME_DIM_PHONE_TABLET
             description: THEME_DIM_PHONE_TABLET_DESCRIPTION
             options:
                '1': THEME_DIM_ONE
                '2': THEME_DIM_TWO
                '3': THEME_DIM_THREE
                '4': THEME_DIM_FOUR
```
