### ISSUE TITLE
Unable to clear content of select fields (multiple:true) in plugin configuration forms

### ISSUE THREAD

**Issue by parcand** [getgrav/grav-plugin-admin#1229]
![capture](https://user-images.githubusercontent.com/22176950/30705803-811037c2-9ec4-11e7-9d61-78fb1495e6fb.gif)

This problem does not occur when saving pages data/frontmatter. It only seems to affect config files. I suspect that it could have something to do with the way arrays are being merged in config files. 

```yaml       
someselect:
  type: select
  label: Preface
  multiple: true
  options:
    'ABC': 'ABC'
    'DEF': 'DEF'
    'GHI': 'GHI'
  use: keys
  validate:
    type: commalist
```
[someplugin.zip](https://github.com/getgrav/grav-plugin-admin/files/1322109/someplugin.zip)

**Comment by parcand** [comment]
The problem is quite obvious when using the `toggleable:true` attribute.

![capture2](https://user-images.githubusercontent.com/22176950/30712658-c805d360-9eda-11e7-8d0c-87d85057076d.gif)

**Comment by rhukster** [comment]
I know this was fixed a while back but it seem to have reappeared.  I'll check it out.

**Comment by rhukster** [comment]
I think the problem is that this field is actually a select box underneath with the ability to choose multiple items.  What that means is that select boxes only work when you select 'something'.  If you remove all the items, the select is sent without any data, so its as if it's not sent at all, so the old value is used.

Really the only way I can think to get around this is to create a 'None' Item that you must pick from if you don't want any:

```
      selectize:
        allowEmptyOption: true
      options:
        '': 'None'
        'ABC': 'ABC'
        'DEF': 'DEF'
        'GHI': 'GHI'
```

The allowEmptyOption is required or the default behavior is to use the empty value as the `placeholder`.

**Comment by rhukster** [comment]
I actually have a better option:

```
    someselect:
      type: selectize
      label: Preface
      selectize:
        options:
          - text: ABC
            value: ABC
          - text: DEF
            value: DEF
          - text: GHI
            value: GHI
      validate:
        type: commalist
```

This uses the selectize comma list and passes the options.  More information here: https://github.com/selectize/selectize.js/blob/master/docs/usage.md

**Comment by parcand** [comment]
That's a pretty good solution. There seems to be one little glitch though. Selected items are properly saved but for some reason, using the `options` setting prevents the selectize widget from properly displaying more than one selected item when the page is reloaded after being saved.

It seems to work however if the list of selected items is provided through the `items`settings. But this quite impractical in the context of config blueprints.

```yaml
someselect:
      type: selectize
      label: Preface
      selectize:
        items:
          - ABC
          - DEF
        options:
          - text: ABC
            value: ABC
          - text: DEF
            value: DEF
          - text: GHI
            value: GHI
      validate:
        type: commalist
```

In order to make it dynamic, I tried using `config-items@: plugins.someplugin.someselect` but it does not work since it display values that were in the config file prior to the save operation.
