### ISSUE TITLE
Unable to add multilevel value for header.content.items using custom tab maked by page blueprint 

### ISSUE THREAD

**Issue by underr-ua** [getgrav/grav-plugin-admin#1240]
Hi!
I want to have page blueprint which helps me to add and change page content items, and i want to use something like this 

```
content:
    items:
        taxonomy@:
            category: notes
```

I try to make custom tab for page for add item value:

```
fields:
    header.content.items:
        type: textarea
        label: Items
        default: 'taxonomy@.category:  notes '
        validate:
            required: false
            type: string
```
If i use expert mode and add items value like `{taxonomy@: { 'category': 'notes'}}` grav parses this code and adds needed indents while save page. But i can't find any working method to store multiline value for item from my custom tab maked by page blueprint. 

P.S.: Sorry for my English, please.
