### ISSUE TITLE
Using lint: true with theme blueprints.yaml console error occurs

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav-plugin-admin#1245]
When using `lint: true` with theme `blueprints.yaml` console error appear :
`Error: window.CSSLint not defined, CodeMirror CSS linting cannot run.`
````
                el_favicon:
                  classes: frontmatter
                  type: editor
                  label: THEME_CSS
                  autofocus: true
                  codemirror:
                  mode: 'text/html'
                  theme: 'monokai'
                  indentUnit: 4
                  autofocus: true
                  indentWithTabs: false
                  lineNumbers: true
                  styleActiveLine: true
                  gutters: ['CodeMirror-lint-markers']
                  lint: true
````
