### ISSUE TITLE
unset-uploads@: true not working anymore

### ISSUE THREAD

**Issue by normanwink** [getgrav/grav-plugin-admin#1256]
I just installed Grav v1.3.8.
As far as I remember, I have been using v1.3.6 before and my blueprints worked flawlessly. Now with the update, `unset-uploads@: true` is being ignored, while I still can unset the content field.

```
title: TITLE

@extends: default

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab
          title: PLUGIN_ADMIN.CONTENT

          fields:
              
            unset-uploads@: true
            unset-content@: true
            
            header.title:
              ordering@: 0
              type: text
              autofocus: true
              style: vertical
              label: PLUGIN_ADMIN.TITLE
              
            header.bgimage:
                type: file
                label: Background Image
                multiple: false
                destination: "self@"
                accept: image/*
```
