### ISSUE TITLE
taxonomy corrupted when saving from admin panel

### ISSUE THREAD

**Issue by ThosG** [getgrav/grav-plugin-admin#1269]
Found this with the 'bones' theme; confirmed with fresh install of Grav with Antimatter. After manually creating tags for a page, when I edit the page in the admin panel the tag fields show up but when I save it, they are overwritten with the string 'Array'.

My user/config/site.yaml file says 
`taxonomies: [category,tag,author]`
File themes/antimatter/blueprints/showtags says 
```
 header.taxonomy:
        type: taxonomy
        multiple: true
```
An example showtags.md file says, **before** saving from the admin panel:
```
taxonomy: 
    tag: [animal, dog]
    author: ksmith
```
After saving, the same file says:
`taxonomy: Array`
The admin panel says 'successfully saved' but the fields for tag, category and author are cleared.

PHP version: 5.6.30. Hosted on shared server under Apache.

I presume this is a bug.

**Comment by rhukster** [comment]
taxonomy should always be an array.  Your page should have:

```yaml
taxonomy: 
    tag: [animal, dog]
    author: [ksmith]
```

or alternatively:

```yaml
taxonomy: 
    tag:
       - animal
       - dog
    author:
       - ksmith
```

Then they should display fine in the  `Options` -> `Taxonomy` Section of any page.

**Comment by rhukster** [comment]
BTW the definition for this is in `system/blueprints/pages/default.yaml`:

```
              fields:
                header.taxonomy:
                  type: taxonomy
                  label: PLUGIN_ADMIN.TAXONOMY
                  multiple: true
                  validate:
                    type: array
```

The `type: array` is key.
