### ISSUE TITLE
[Bug?] Saving page replaces values in field with type: taxonomy to the same as in Taxonomy section

### ISSUE THREAD

**Issue by pshe94** [getgrav/grav-plugin-admin#1291]
Hi,
I have custom page template (let's call it Collection), that extends the default template. In Yaml file of Collection template, I've added my own field (let's call it Group by field) with `type: taxonomy`. In page settings, I've set some values in the original Taxonomy field (from the default template, in Options tab) and my own. Unfortunately after saving, my values in Group by field are replaced with values from original Taxonomy field (from default template), but in Frontmatter in Expert mode, values are as they should be.

Is this some kind of bug, or should I just create completely custom field? I tried using field with `type: selectize`, but I haven't yet found a way to add tags and categories from taxonomy to "auto completion" list.

Here is an image to show the problem, because my English isn't very good, and I'm pretty bad at explaining...
![Problem](https://user-images.githubusercontent.com/34661843/34128772-161d0850-e442-11e7-84e0-824eeaae056b.jpg)

collection.yaml

```
title: Test
extends@:
  type: default
  context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        options:
          fields:

            spacer:
              type: spacer
              title: Another taxonomy

            header.group_by:
              type: taxonomy
              label: PLUGIN_ADMIN.TAXONOMY
              multiple: true
              validate:
                type: array
```

default.yaml
```
title: Default
extends@:
  type: default
  context: blueprints://pages
```

**Comment by rhukster** [comment]
You can't use taxonomy field more than once, as it's a special field.  I think what you are looking for is perhaps selectize with commalist?

```
                pages.ignore_folders:
                    type: selectize
                    size: large
                    label: PLUGIN_ADMIN.IGNORE_FOLDERS
                    help: PLUGIN_ADMIN.IGNORE_FOLDERS_HELP
                    classes: fancy
                    validate:
                        type: commalist
```

for example...
