### ISSUE TITLE
filepicker field: JPG extension images are ignored

### ISSUE THREAD

**Issue by tranduyhung** [getgrav/grav-plugin-admin#1295]
Hi,

In my blueprint I setup my ```filepicker``` field like this:

```
                header.my_field:
                  label: Image
                  type: filepicker
                  folder: '@self'
                  preview_images: true
                  accept:
                    - .png
                    - .jpg
```

But the field doesn't show *.JPG files. Should the field include JPG and PNG images in the list by default? "JPG" or "jpg" is just the way we type and save the files, they are all the same file type.
