### ISSUE TITLE
File upload (defined in blueprints)

### ISSUE THREAD

**Issue by kroegerama** [getgrav/grav-plugin-admin#13]
I have defined the following in the blueprints file of my theme (/user/themes/mytheme/blueprints/default.yaml) to add a new tab "Downloads" to each page's admin panel:
```
form:
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        downloads:
          type: tab
          title: Downloads
          fields:
            downloads:
              type: section
              title: Downloads
              underline: true
            header.downloads:
              type: list
              label: Downloads
              fields:
                .title:
                  type: text
                  label: Title
                  default:
                  validate:
                    required: true
                .file:
                  type: upload
                  label: File
                .icon:
                  type: text
                  label: Icon
                  default:
                  validate:
                    required: false
```
This works fine and the new tab is displayed. However, if I click on "save", the file won't upload and the page header contains:
```
file: 'C:\fakepath\test.bin'
```
The **fakepath** part is a security feature of Chrome. Grav should only use the last part of the filename.

*(I'm not sure, if this is a problem with the admin plugin or with the forms plugin. Sorry, if I'm wrong here.)*
