### ISSUE TITLE
Toggleable field in fieldset inside of list is always getting checked

### ISSUE THREAD

**Issue by pshe94** [getgrav/grav-plugin-admin#1313]
Adding toggleable field inside of fieldset, which is inside of list gets always checked after saving, even without any value inside of that field.

```
header.list:
  type: list
  label: List
  fields:
    .fieldset:
      type: fieldset
      title: Fieldset
      fields:
        .fieldset.toggleable:
          type: text
          label: Text
          toggleable: true
        .fieldset.text:
          type: text
          label: Text
```
