### ISSUE TITLE
Validate.rule:slug doesn't work in default.yaml

### ISSUE THREAD

**Issue by newmedicine** [getgrav/grav-plugin-admin#1343]
```
                    folder:
                      type: text
                      label: PLUGIN_ADMIN.FOLDER_NAME
                      validate:
#                        rule: slug
                        pattern: '[a-zA-Zа-яA-Я0-9_\-]+'
                        min: 1
                        max: 200
```
`rule: slug` in `default.yaml` doesn't appear to be being parsed (I've commented it out here of course). If I copy `pattern` etc from the top of the file into the `validate` section, it works as expected. If I just inherit (extend) `default.yaml` in theme blueprints no validation will take place.

Is this a bug?

Cheers, Nick
