### ISSUE TITLE
Translate login page to default lang

### ISSUE THREAD

**Issue by antonlukin** [getgrav/grav-plugin-admin#1361]
Can't translate login page to default language.

My system.yaml
```
languages:
  translations: true
  supported:
    - ru
```

and site.yaml
```
default_lang: ru
```
but my login page still english translated. It seems that this code prevents translating:
https://github.com/getgrav/grav-plugin-admin/blob/77ee70b8cf7cb84c881edcde9199eb7fdb2bb82d/classes/admin.php#L464
