### ISSUE TITLE
Mediapicker inside a list field : Unable to display child page when clicking on fa-plus

### ISSUE THREAD

**Issue by paulmassen** [getgrav/grav-plugin-admin#1369]
Hi, 

This is a problem with latest Grav + Admin.

When opening the mediapicker, it is not possible to click on the fa-plus in order to display child pages.
![image](https://user-images.githubusercontent.com/12809352/37145487-4cdcddd0-22c1-11e8-9e45-3eca9f8bc3a8.png)

It also looks like mediapicker is having trouble fetching medias on subpages.

Thanks!

**Comment by OleVik** [comment]
Are there any errors thrown in console?

**Comment by paulmassen** [comment]
nope, no error in console

**Comment by paulmassen** [comment]
Oh, this is not related to Grav version actually.

The problem occurs when the mediapicker is in a list field.
I will rename the issue
Here is an example blueprint:

```
title: Artiste
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            header.press_review:
              type: list
              label: Ajouter un extrait de presse
              btnLabel: Ajouter extrait de presse
              controls: both
              fields:
                .name:
                  type: text
                  label: Nom du média
                .content:
                  type: textarea
                  label: Corps du texte de l'extrait
                .author:
                  type: text
                  label: Auteur
                .logomedia:
                  type: mediapicker
                  label: Choisir logo media
                  placeholder: Format carré de préférence
```
