### ISSUE TITLE
double entries are saved in taxonomy fields

### ISSUE THREAD

**Issue by manuel-84** [getgrav/grav-plugin-admin#1375]
I have a custom blueprint with

```
            header.taxonomy:
              type: taxonomy
              label: PLUGIN_ADMIN.TAXONOMY
              multiple: true
              validate:
                type: array
```

Since the last update (today) every time I save the page in frontmatter I can see that the entries are added and duplicated
