### ISSUE TITLE
Editor field throws JS error when marked as `required`

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav-plugin-admin#1393]
Based on this field definition:

```
            header.some_content:
              type: editor
              label: Full title
              validate:
                 required: true
```

This throws a JS error on save with error:

```
An invalid form control with name='data[header][some_content]' is not focusable.
```

Removing the `validate:` element does not throw an error and save works as expected.
