### ISSUE TITLE
Metadata og is broken to saving in Admin plugin.

### ISSUE THREAD

**Issue by Unrealno1** [getgrav/grav-plugin-admin#140]
Page metadata:
```
og:
    title: The Rock
    type: video.movie
    url: http://www.imdb.com/title/tt0117500/
    image: http://ia.media-imdb.com/images/rock.jpg
```

After, this saved in admin plugin.
```
og: 'The Rock, video.movie, http://www.imdb.com/title/tt0117500/, http://ia.media-imdb.com/images/rock.jpg'
```
