### ISSUE TITLE
Select form field doesn't select actual value in list field

### ISSUE THREAD

**Issue by superDuperCyberTechno** [getgrav/grav-plugin-admin#1413]
If you add a select field to a list element in a template blueprint, the select will not mark the correct option as selected when the page editor is loaded. It simply attributes selected to the first element.

**Comment by w00fz** [comment]
@superDuperCyberTechno I tried replicating what you described but this works fine for me.

This is my testing:

```
title: Testing issue #1413
@extends:
    type: default
    context: blueprints://pages

form:
    fields:
        header.my_test:
            name: items
            type: list
            label: Items
            help: Help
            collapsible: true
            fields:
              .title:
                type: text
                label: Title
              .number:
                 type: select
                 label: Number
                 options:
                    '1': One
                    '2': Two
                    '3': Three
                    '4': Four
              .letter:
                 type: select
                 label: Letter
                 options:
                    - a
                    - b
                    - c
                    - d
```

I loaded it, added a new item, selected `Four` and `d`, saved. On next load those items were properly selected.
I also tried adding more items and picking different values, it just seems to work fine for me.

<img width="401" alt="select in list" src="https://user-images.githubusercontent.com/11734/40796696-c4c3d174-64ba-11e8-9831-389fe53d68db.png">

Am I missing something?
