### ISSUE TITLE
Add a plain text field for blueprints and forms

### ISSUE THREAD

**Issue by mikegcox** [getgrav/grav-plugin-admin#143]
It would be nice to be able to write some instructions to users on how to edit the content of their website.  For example, a homepage template that makes use of fontawesome.  I know what fontawesome is, but it would be nice to put an explanation and perhaps a link for those that do not.

The biggest issue I find with a CMS is explaining to end users how to edit their content without screwing it up.  Grav is the answer to this problem where we as website developers can blueprint the admin forms so that content administrators don't mess up our hard work yet they can edit what they need to.  A place where the developer can make notes to content administrators would really help.

A plain text field-type would work well for this.

**Comment by rhukster** [comment]
I took the "display" field that never really got finished and flushed it out:

```
test:
  type: display
  size: large
  label: Instructions
  markdown: true
  content: "This is a test of **bold** and _italic_ in a text/display field\n\nanother paragraph...."
```

![2015-09-05-12-6cyih](https://cloud.githubusercontent.com/assets/1084697/9700727/669dab22-53cb-11e5-9f0b-c78003d5177d.png)
