### ISSUE TITLE
Page editor doesn't show Publishing etc

### ISSUE THREAD

**Issue by ThosG** [getgrav/grav-plugin-admin#1435]
The page editor doesn't show the options for Publishing and Taxonomies, even though my accounts file apparently gives me super-admin access:
```
access:
  admin:
    login: true
    super: true
  site:
    login: true
```

Grav v1.4.3 - Admin v1.7.4. Tried with Bones and Quark.

**Comment by jgonyea** [comment]
Hi, @ThosG .  Can you check your second tab, the one called "Options"?  What do you see there?  Also, what theme are you using?

**Comment by ThosG** [comment]
Hi @jgonyea 

Theme: tried with Bones and Quark on different sites. I'm attaching a screenshot of what I see on the Options tab. BTW the Options tab doesn't show up at all in Normal mode, only in Expert mode.

![screenshot of options tab](https://user-images.githubusercontent.com/11003463/39394904-8d254504-4acf-11e8-8d20-10c357920958.jpg)

**Comment by ThosG** [comment]
@rhukster Here it is.
```
title: Published-item

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        item:
          type: tab
          title: Form for Published Items

          fields:
            header.full_title:
              type: editor
              help: Complete title; see docs for use of bold and italics
              label: Full title
              validate:
                required: true

            header.edition:
              type: text
              label: eg ‘Chorus score’(see Wel 1-2) or ‘transposed edition’ (CVR 3207); for pieces that appear in two or more versions

            header.subtitle:
              label: subtitle, e.g. 'A masque'
              type: editor
              label: Subtitle
              rows: 1
              size: x-small
 
            header.JPHref:
              label: link to the JPH site
              type: text
              label: JPH link
                   
            header.ensemble:
              type: text
              label: Ensemble (eg soprano, 2 violins, and bc)
              validate:
                required: true

            header.composer:
              type: text
              label: Composer
              validate:
                required: true

            header.editor:
              type: text
              label: Editor
              help: Use this for 'Edited by PDQ Bach' or 'Introduction by A. Scholar'.
          

            header.itemlist:
              name: itemlist
              type: list
              label: List of items, eg a list of songs. One item per line. Click Add item to start
              fields:
                .an_item:
                 type: text
                 label: an item
              
            header.title:
              type: text
              label: Reference No
              validate:
                required: true
          
            header.price:
              type: text
              label: Price in GBP (no £ sign please)
              validate:
                required: true

            header.featured:
                help: set to 1 if you want to mark this 'New'
                type: toggle
                label: featured as new?
                default: 0
                options:
                    1: PLUGIN_ADMIN.YES
                    0: PLUGIN_ADMIN.NO
                validate:
                    type: bool
            
            header.in_prep:
                help: Mark to appear under Future Titles
                type: toggle
                label: in preparation?
                default: 0
                options:
                    1: PLUGIN_ADMIN.YES
                    0: PLUGIN_ADMIN.NO
                validate:
                    type: bool

            header.cover_image:
              type: file
              label: cover image - JPG
              filesize: 2
              destination: '@self'
              accept:
                - image/*

            header.sample_page:
              type: file
              label: Sample music page - PDF
              destination: '@self'
              filesize: 2
              accept:
                - application/pdf
                - application/x-pdf

            header.searchable:
              type: toggle
              label: searchable? - normally Yes
              default: 1
              options:
                    1: PLUGIN_ADMIN.YES
                    0: PLUGIN_ADMIN.NO
              help: best to leave this alone
              validate:
                type: bool
                required: true
          
            header.visible:
              type: toggle
              label: visible? - set to No
              default: 0
              options:
                    1: PLUGIN_ADMIN.YES
                    0: PLUGIN_ADMIN.NO
              help: best to leave this alone
              validate:
                type: bool
                required: true
          
            content:
                type: editor
                label: Full description
                size: large
```
