### ISSUE TITLE
Undefined property: stdClass::$image in 1.8.2

### ISSUE THREAD

**Issue by superDuperCyberTechno** [getgrav/grav-plugin-admin#1454]
I get the error `Undefined property: stdClass::$image` when uploading an image to a page template. The error handler specifically references [line 722 in adminbasecontroller.php](https://github.com/getgrav/grav-plugin-admin/blob/develop/classes/adminbasecontroller.php#L722). The image specific blueprint is here:

```
            header.image:
                type: file
                label: Screenshot
                limit: 1
                destination: 'self@'
                multiple: false
                style: vertical
                accept:
                  - image/*
```

The image gets uploaded regardless of error, but the header is not updated...

Rolling back to 1.8.1 fixed it for now.

**Comment by rhukster** [comment]
Don't do this, pagemedia field already uploads to the page folder.  File field is intended to be used in other non-page blueprints.

**Comment by superDuperCyberTechno** [comment]
So, what would the correct way be to achieve this, blueprint wise?

**Comment by herrbischoff** [comment]
Same here. Since the update to Grav 1.4.5 and Admin 1.8.2, I cannot upload images, resulting in the same error @superDuperCyberTechno reported.

My blueprint excerpt is a follows:

```
header.images:
  type: file
  label: Images
  random_name: true
  multiple: true
  limit: 2
  destination: 'assets'
  filesize: 10
  accept:
    - image/*
```

This has worked thus far without issue. The update broke it.

If there are breaking changes, it would be advantageous to know about them **before** the update. If there are best practices, it would be great to know about the **at all** instead of just getting a response like

> Don't do this, pagemedia field already uploads to the page folder. File field is intended to be used in other non-page blueprints.

without any pointers as to why. I created the blueprint according to the documentation at the time and it worked. Either this is a bug or a breaking, non-documented change.
