### ISSUE TITLE
Selectize-field misbehaving

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav-plugin-admin#1461]
The recent [change](https://github.com/getgrav/grav-plugin-admin/blob/dd8837519ae371172dd78c7e060cfaa2dceeb9f0/themes/grav/templates/forms/fields/selectize/selectize.html.twig) to the Selectize-field broke its ability to merge existing items, which had been implemented [previously](https://github.com/getgrav/grav-plugin-admin/blob/c4810670361b32f44ef5b6ea755a8765cfe6a3bf/themes/grav/templates/forms/fields/selectize/selectize.html.twig).

In a specific scenario, such as overriding taxonomies:

```
taxonomies:
  type: section
  title: PLUGIN_ADMIN.TAXONOMIES
  underline: true
  fields:
    header.taxonomy:
      unset@: true
    header.taxonomy.category:
      type: select
      label: Category
      help: Sets the state of the project
      highlight: 0
      data-options@: '\Grav\Theme\ProjectSpace::categories'
    header.taxonomy.tag:
      type: selectize
      label: Tags
      help: Applies tags to the project
      selectize:
        options:
          - text: ABC
            value: ABC
          - text: DEF
            value: DEF
          - text: GHI
            value: GHI
          - text: JKL
            value: JKL
          - text: MNO
            value: MNO
          - text: PQR
            value: PQR
          - text: STU
            value: STU
          - text: VWX
            value: VWX
          - text: YZ
            value: YZ
      validate:
        type: commalist
```

Using this post.md:

```
---
title: 'Mediator Theme Setup'
image: tools.jpg
color: red
date: '05-02-2014 00:00'
taxonomy:
    category: idea
    tag:
        - ABC
        - DEF
        - GHI
        - JKL
        - MNO
slug: theme-setup
---
```

Leaving out `|merge({'items':value})` causes only the first item to be loaded, the subsequent values are removed when the DOM finishes loading:

![image](https://user-images.githubusercontent.com/974717/40975174-5d67ba72-68ca-11e8-842c-4b9cec19e45e.png)

Whereas adding it back in to [selectize.html.twig](https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/templates/forms/fields/selectize/selectize.html.twig#L4), from:

 `data-grav-selectize="{{ (field.selectize is defined ? field.selectize|merge({'create': true}) : {'create': true})|json_encode()|e('html_attr') }}"`

to

`data-grav-selectize="{{ (field.selectize is defined ? field.selectize|merge({'create': true})|merge({'items':value}) : {'create': true})|json_encode()|e('html_attr') }}"`

makes it work again:

![image](https://user-images.githubusercontent.com/974717/40975255-a041e570-68ca-11e8-8f8d-c3b45db065d7.png)

I submit this as an issue rather than a PR to also ask about the use of `selectize: options` rather than just `options: `. The latter is more in line with blueprints generally. The logic of #1236 seems sound, but why was the [reversal](https://github.com/getgrav/grav-plugin-admin/commit/dd8837519ae371172dd78c7e060cfaa2dceeb9f0#diff-eda52bf4e7843717213ca8079b1747e5) necessary? Seemingly for selectize-plugins, but how does that differ from the existing implementation?
