### ISSUE TITLE
Folder field on filepicker seems broken

### ISSUE THREAD

**Issue by Lazza** [getgrav/grav-plugin-admin#1465]
I have updated to 1.8.3 and now the `folder` field in my custom blueprint does not seem to work anymore:

```
header.brands_1:
  type: filepicker
  folder: 'theme@:/images/brands'
  preview_images: true
  toggleable: true
```

In previous versions, it used to list files that are in my theme folder, now it shows files in the page. How can I overcome this problem?

Thank you.

**Comment by mahagr** [comment]
@Lazza @pamtbaau I fixed the issue, if you need the fix right away, please see my fix. :)

**Comment by Lazza** [comment]
@mahagr unfortunately it does not seem to work properly. Is there any debug info I should provide?

**Comment by pamtbaau** [comment]
@Lazza The fix has not yet been merged into the master branch.
When I clone the develop branch into my user/plugin/admin folder, it works fine for me.

**Comment by Lazza** [comment]
@pamtbaau I will try... but why is the commit mentioned in the release notes for 1.8.4 then? 😅

**Comment by nerikh** [comment]
Has this fix been applied to whichever branch is being used when updating the plugin from the admin panel?  The 'folder' field is not working for me.  I'm using all the latest codebase.

**Comment by nerikh** [comment]
FYI -- Tested Developer branch as well, and not able to get it to work.  Still shows the images directly within the @self page instead of images from any other directory specified in 'folder'

.text_image__image:
          type: filepicker
          folder: 'theme@:/images/pages'
          preview_images: true
          acccept:
              - .png
              - .jpg
              - .gif
              - .svg

**Comment by mahagr** [comment]
This works just fine in Admin 1.9.12 for me.

**Comment by mahagr** [comment]
Used this page blueprint to test the issue:

```yaml
extends@: default

form:
  fields:
    tabs:
      fields:
        image:
          type: tab
          title: Image
          fields:
            header.text_image__image:
              type: filepicker
              label: Image
              folder: 'theme@:/images'
              preview_images: true
              acccept:
                - .png
                - .jpg
                - .gif
```
