### ISSUE TITLE
Backspace button or trash icon not clean date in blueprint datefield

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-plugin-admin#1493]
Hello!

I use `datefield` in admin blueprint:
```yaml
header.date:
    type: datetime
    label: Дата отправления
```

And I can't delete date without `toggleable: true`:
![3](https://user-images.githubusercontent.com/7556290/43238699-f36fc312-9097-11e8-829a-7a0ef6f433d9.gif)

I spent half an hour looking for what's the reason and it was `toggleable: true` option/checkbox.
Maybe need to change this behavior for better user experience?
