### ISSUE TITLE
Page Blueprint does not appear 

### ISSUE THREAD

**Issue by lowepe** [getgrav/grav-plugin-admin#1495]
Hey,

I have a issue with a page blueprint. I don't know what I'm missing. 

When I use this code it appears to the admin backend: 

```
title: Mitglieder
'@extends':
  type: default
  context: blueprints://pages

form:
  fields:
    tabs:
      types: tabs
      active: 1

      fields:
        test:
          type: tab
          title: Mitglieder
          fields:
            header.mitglied:
              type: list
              fields:
                .name:
                  type: text
                  label: Vor- und Nachname
                .file:
                  type: file
                  label: Foto vom Mitglied 
                  destination: 'theme@:/assets/members'
                  blueprint: 'themes.theme'
                  accept:
                    - image/*
```

But when I simply add a new field to the list the tab disappears				
```
              fields:
                .name:
                  type: text
                  label: Vor- und Nachname
                .titel:
                  type: text
                  label: Titel                
                .file:
                  type: file
                  label: Foto vom Mitglied 
                  destination: 'theme@:/assets/members'
                  blueprint: 'themes.theme'
                  accept:
                    - image/*             
```

Anyone have a solution?
