### ISSUE TITLE
iconpicker issue theme blueprint list field

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav-plugin-admin#1538]
Found issue using `file picker`field in `list`field

![](https://i.imgur.com/kW1GEpd.png)
When click on `file picker` in second item icon dropdown appears in the first item, and if the first item is collapsed you see nothing (see screenshot) 
````
amp_menu_items:
              name: menuitems
              type: list
              collapsed: true
              label: THEME_ELANA_ITEMS
              help:
              fields:
                .title:
                  type: text
                  label: THEME_ELANA_TITLE
                  help: THEME_ELANA_TITLE_HELP
                .icon:
                    type: iconpicker
                    label: THEME_ELANA_ICON
                    toggleable: false
````
