### ISSUE TITLE
Groups text input resetting itself when setting user "Groups" at "Access levels" part on "/admin/user/exampleusername"

### ISSUE THREAD

**Issue by Daryadi-S** [getgrav/grav-plugin-admin#1548]
The Groups text input always revert back to null when hitting the save button.

![screenshot-20181119_221329](https://user-images.githubusercontent.com/45057935/48715795-67519380-ec48-11e8-8bb0-b0f452cc9f33.png)

**Comment by rhukster** [comment]
Groups must first be defined in `user/config/groups.yaml` before you can pick/select them:

```
downloaders:
  access:
    site:
      download: true

restricted:
  access:
    site:
      login: true
      restricted: true
```

More info: https://learn.getgrav.org/advanced/groups-and-permissions#defining-groups
