### ISSUE TITLE
Blueprint File delete error

### ISSUE THREAD

**Issue by whollaus** [getgrav/grav-plugin-admin#1558]
[Latest Admin Version]

I add one file field (Blueprint see below)

After that I upload a file and click on Save:
![grafik](https://user-images.githubusercontent.com/4582757/49998636-13ab3f00-ff95-11e8-9209-97f5242cf047.png)

Click on delete:
![grafik](https://user-images.githubusercontent.com/4582757/49998691-3b020c00-ff95-11e8-9360-5cdcc268f631.png)

This error is shown:
![grafik](https://user-images.githubusercontent.com/4582757/49998748-566d1700-ff95-11e8-8d78-723a8b3f0a6f.png)

When I click on Save, the file is away from the additional file field, but still available at the server
![grafik](https://user-images.githubusercontent.com/4582757/49998857-a6e47480-ff95-11e8-88b7-96e2a8ba3d9a.png)

Thank you very much.

```
extends@: default

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            header.image1:
              type: file
              label: Image
              avoid_overwriting: true
              destination: '@self'
              multiple: false
              style: vertical
              accept:
                - image/jpg
                - image/jpeg 
```
