### ISSUE TITLE
Saving blog gives me "Missing required field: Max Item Count"

### ISSUE THREAD

**Issue by vladaman** [getgrav/grav-plugin-admin#1570]
While saving Blog in Admin I gen an error: **Missing required field: Max Item Count**. This happens, when I change Blog template from default to Blog. Then this Max Item Count is actually empty. Then I save it again and it works.

Grav v1.5.6 - Admin v1.8.15

Yaml:
```
 header.content.limit:
              type: text
              label: Max Item Count
              default: 5
              validate:
                required: true
                type: int
                min: 1
````
