### ISSUE TITLE
Multiple Images in pagemediaselect returns 'array'

### ISSUE THREAD

**Issue by garytube** [getgrav/grav-plugin-admin#1580]
`                header.section.planning.images:
                    type: pagemediaselect
                    multiple: true
                    label: Choose media
`
I have multiple fieldsets each containing a pagemediaselect.
In each fieldset the user is allowed to add  up to X images from the page media pool.

Selecting works fine but when saving the page, all I get is 'array'
![image](https://user-images.githubusercontent.com/3823504/50772066-ccab2380-128c-11e9-8856-2b5edb55bde5.png)

what am I missing?

**Comment by rhukster** [comment]
Seems there's a few 'media' related issues been posted over the holidays.  I'll try to dig into them all at the same time when I get caught up with everything.

**Comment by rhukster** [comment]
Can you please provide the full example of your blueprint where the field is defined.

**Comment by mahagr** [comment]
Can you try adding

```
  array: true
```

to the `pagemediaselect` field?

If it works, I can easily fix this issue so you don't need to add it manually.

**Comment by justusthane** [comment]
Hey @mahagr 

Thanks for the response. Unfortunately no change in behavior after adding **array: true**

![image](https://user-images.githubusercontent.com/626445/53290592-70cd2900-376c-11e9-96a7-9d6f77bf3420.png)

There's nothing else I would have to do to get that to "take effect", correct? I did restart the PHP server just in case.

**Comment by mahagr** [comment]
No, that should be all good. I'm starting to think that the field doesn't support `multiple`, can you send me the resulting yaml file for the data?

**Comment by code9dev** [comment]
Please help how to display multiple images in html twig file

**Comment by mahagr** [comment]
Works just fine for me in Admin 1.9.12. Please reopen if it is still an issue.

**Comment by mahagr** [comment]
Actually I was wrong.

* Create page type with:
```
extends@: default

form:
  fields:
    tabs:
      fields:
        image:
          type: tab
          title: Image
          fields:
            header.gallery:
                type: pagemediaselect
                style: vertical
                label: Page Gallery
                multiple: true
```

* Create page of this type and add few images
* Save
* Add all images to the field
* Save

Resulting page:
```
title: filepicker
media_order: 'github-settings.png,grav-parent-field-broken.png'
text_image__image: favicon.png
gallery: ''
```
