### ISSUE TITLE
duplicate toggles on forms with multiple extends@ values

### ISSUE THREAD

**Issue by grisaa** [getgrav/grav-plugin-admin#1603]
i have a template form that i want to extend multiple other forms. so i added multi
i've done many variations — template3.yaml:
```yaml
extends@:
  - template1
  - template2
```
```yaml
extends@:
  - type: template1
  - type: template2
```
```yaml
extends@:
  - type: template1
    context: blueprints://pages
  - type: template2
    context: blueprints://pages
```
including also variations with `@extends`, `'@extends'`, and `'extends@'`. always with the same results. — the template3's toggles appear as many times as there are `extends@`.
<img width="782" alt="screen shot 2019-01-29 at 18 56 13" src="https://user-images.githubusercontent.com/10264696/51948711-9417e900-23f7-11e9-9bc6-c2d17a0e2393.png">
