### ISSUE TITLE
Removing file from filepicker

### ISSUE THREAD

**Issue by dzibus** [getgrav/grav-plugin-admin#1619]

**Comment by mahagr** [comment]
@dzibus Where are you using the file picker? and what are the strings in path and destination variables?

**Comment by dzibus** [comment]
sorry, i meant _file_ not _filepicker_

i have a section with _file_ field
```
images:
  type: section
  title: Upload Media
  underline: true

  fields:
    header.impression_images:
      type: file
      label: Impressions Desktop
      destination: '@self/impressions/desktop'
      multiple: true
      limit: 0
      accept:
        - 'image/*'
        - 'video/*'
```
