### ISSUE TITLE
Scheduler backup jobs (1.60rc3)

### ISSUE THREAD

**Issue by matchavez** [getgrav/grav-plugin-admin#1623]
I've searched, and this doesn't seem to be out there...

Problem: On MacOS, I have put the crontab entry for the scheduler in, and it shows "Ready". As an example, the backup job is set to run at 3am. However, in backups, they don't appear to have been created.

First, if scheduler runs a backup, should it show up in the backup UI, or is it separate?

Second, if it says that the run is "Ready", and the backup process works in the UI, is that all I should need?

Thanks.

**Comment by rhukster** [comment]
what result to you have if you run:

```
crontab -l
````

This should output all the jobs registered in your system cron. Miine looks like this:

```
 $  crontab -l                                                                                           
* * * * * cd /Users/rhuk/grav;/usr/local/bin/php bin/grav scheduler 1>> /dev/null 2>&1
```

That being the case, what does your 'user/config/scheduler.yaml` looks like?

Mine looks like this:

```
status:
  ls-job: enabled
  cache-purge: enabled
  cache-clear: enabled
  default-site-backup: enabled
  pages-backup: enabled
custom_jobs:
  ls-job:
    command: ls
    args: '-lah'
    at: '* * * * *'
    output: logs/cron-ls.out
    output_mode: overwrite
    email: user@email.com
```

Also what does your `user/config/backups.yaml` look like? Mine looks like this:

```
purge:
  trigger: number
  max_backups_count: 25
  max_backups_space: 5
  max_backups_time: 365
profiles:
  -
    name: 'Default Site Backup'
    root: /
    exclude_paths: "/backup\r\n/cache\r\n/images\r\n/logs\r\n/tmp"
    exclude_files: ".DS_Store\r\n.git\r\n.svn\r\n.hg\r\n.idea\r\n.vscode\r\nnode_modules"
    schedule: true
    schedule_at: '0 3 * * *'
  -
    name: 'Pages Backup'
    root: 'page://'
    exclude_files: .git
    schedule: true
    schedule_at: '* 3 * * *'
```
