### ISSUE TITLE
Translation does not work

### ISSUE THREAD

**Issue by k1ll1n** [getgrav/grav-plugin-admin#1636]
Hi
In the admin panel is included Russian.
In the normal session, it works, but if you open the browser in incognito mode, English will be displayed.

Why it happens?
![unknown (1)](https://user-images.githubusercontent.com/4102348/54893503-b6eee700-4ee8-11e9-8258-4ac526613527.png)

I tried to open it in another browser and on another computer.
English is always displayed.

My settings from `user/config/system.yaml`

```yaml
languages:
  supported:
    - ru
  include_default_lang: false
  translations: true
  translations_fallback: true
  session_store_active: false
  http_accept_language: false
  override_locale: false
```

I tried to rewrite the translation, as it was done [here](https://github.com/getgrav/grav-plugin-admin/issues/422).

Created the path `user/language/ru.yaml`

Nothing helps.
