### ISSUE TITLE
filepicker is not working with sub-directory multi-site.

### ISSUE THREAD

**Issue by amizushiro** [getgrav/grav-plugin-admin#1657]
I am trying to use the filepicker of a blueprint in a subdirectory of a multi-site.
However, even if ' self @ ' is specified, the image list is not displayed at all.
Filepicker I wrote in the main directory blueprint, the list of images came out.

Also, if you type directly into the default.md header, the file name will be displayed, but the thumbnail will be Not found.

Grav: v1.6.6
Admin: v1.9.2

```
    header.image:
      type: filepicker
      label: TestImages
      folder: 'self@'
      preview_images: true
      accept:
        - .jpg
        - .png
```

Could you help me to solve the problem?

thanks.
