### ISSUE TITLE
Path not valid for this data type

### ISSUE THREAD

**Issue by souricevincent** [getgrav/grav-plugin-admin#1669]
Hello, I wish to host my images of pages other than `self@`, I thought to make destination: `image://` to have it here `user/images`. I manage to add them in the right folder since the admin, unfortunately, I can not delete them, I have an error "Path not valid for this data type".

**Comment by educedesign** [comment]
Had the same issue but interestingly enough the solution mentioned in #1619 worked for me. Figured I share my *.yaml in case it helps someone.

```
clients:
     type: section
     title: Clients
     underline: true
     fields:
          header.clients:
               type: file
               label: Client logos
               destination: 'page@:/services/clients'
               multiple: true
               limit: 0
               accept:
                    - image/*
```
