### ISSUE TITLE
Bug with multiple upload fields

### ISSUE THREAD

**Issue by lepascal** [getgrav/grav-plugin-admin#1675]
I have multiple upload fields per page. Every time I delete an image from one of the fields, all images in all other fields are replaced by the images in that field.

Before:

![bildschirmfoto_2018_03_29_um_18_25_58](https://user-images.githubusercontent.com/6012332/38875024-cb9dad0e-4259-11e8-9979-4d5ab4b78710.png)

After trying to delete the first image in the field:
![bildschirmfoto_2018_03_29_um_18_26_10](https://user-images.githubusercontent.com/6012332/38875092-e99f451a-4259-11e8-91b5-a076235b43d3.png)

I already re-downloaded grav and copied the user data to the new install. This is the code of my .yaml:

```
title: Features
@extends: 
    type: default
    context: blueprints://pages 

form:
  validation: loose

  fields:

    tabs:
      type: tabs
      active: 1

      fields:
        content:
          fields:

            header.media_order:
              type: ignore

            
            header.tags:
              name: tags
              type: selectize
              label: Tags
            

                   
            header.homesize:
              type: select
              size: short
              label: Größe des Projektes in der Übersicht
              options:
               full: Ganze Breite
               twothirds: Zwei Drittel
               onethird: Ein Drittel
               half: Halbe Breite
               doubleheight: Ein Drittel, Hochformat
                      
            header.onlyfooter:
              name: onlyfooter            
              type: toggle
              label: Nur im Footer anzeigen
              options:
               1: PLUGIN_ADMIN.YES
               0: PLUGIN_ADMIN.NO
              default: 0    
         
            header.entries:
              name: images
              type: list
              label: Bilder und Videos
              collapsed: 'true'

              fields:
                .images:
                  type: file
                  label: Bilder (mehrere werden automatisch zu Slideshows zusammengefasst)
                  destination: 'page@:/images'
                  random_name: true
                  accept:
                   - 'image/*'
                  multiple: true
                  size: 100
                .slideshow:
                  type: toggle
                  options:
                   1: PLUGIN_ADMIN.YES
                   0: PLUGIN_ADMIN.NO
                  default: 0
                  label: "Mehrere Bilder zu Slideshow zusammenfassen"
                .embed:
                  type: textarea
                  label: Zur Einbettung von Videos Embed-Codes hier einfügen und oberes Feld leer lassen
                .layout:
                  type: select
                  size: short
                  label: Größe des Bildes im Layout
                  options:
                   full: Ganze Breite
                   twothirds: Zwei Drittel
                   onethird: Ein Drittel
                   half: Halbe Breite
                   doubleheight: Ein Drittel, Hochformat
                .backgroundfit:
                  type: select
                  size: short
                  label: Bild einpassen
                  options:
                   fit: Einpassen
                   fill: Ausfüllen
                  default: "fill"
                .backgroundcolor:
                    type: colorpicker
                    label: Hintergrundfarbe
                    placeholder: '#00000'
                .onfront:
                  type: toggle
                  options:
                   1: PLUGIN_ADMIN.YES
                   0: PLUGIN_ADMIN.NO
                  default: 1
                  label: "In der Projektübersiht anzeigen"
                .coverimage:
                  type: toggle
                  options:
                   1: PLUGIN_ADMIN.YES
                   0: PLUGIN_ADMIN.NO
                  default: 0
                  label: "In der Übersicht als erstes Bild anzeigen"
```
