### ISSUE TITLE
Malformed blueprints cause GPM connection failure

### ISSUE THREAD

**Issue by N-Parsons** [getgrav/grav-plugin-admin#1692]
This issue was first noted in getgrav/grav#1699, but since it's presumably an issue with the Admin plugin, I thought it best to open an issue here.

When a theme blueprint contains incorrect indentation, no error is displayed other than that a connection to GPM cannot be established (for both themes and plugins). This is obviously not a very clear error message that led me to check all of the known issues that can cause that error message, before looking at the blueprint and finding the cause.

Example blueprint, in which `options` is over-indented:
```
form:
  single_page.enabled:
    type: toggle
    label: Single page mode
    highlight: 1
    default: 0
      options:
        1: PLUGIN_ADMIN.ENABLED
        0: PLUGIN_ADMIN.DISABLED
  validate:
    type: bool
```
