### ISSUE TITLE
Page with form disallows saving

### ISSUE THREAD

**Issue by lukecurtis93** [getgrav/grav-plugin-admin#1695]
I have a `landing.md` file with the following in the md file
```
form:
    name: contact

    #
    # Add your custom fields here.
    # These fields will be available in the page's Content tab
    # inside the Admin Panel.
    #
    fields:

        #
        # Form itself
        #
        name:
            display_label: false
            placeholder: NAME
            type: text

        phone:
            display_label: false
            placeholder: PHONE NUMBER
            type: text

        email:
            display_label: false
            placeholder: EMAIL ADDRESS
            type: email
```

However everytime I press save now I get the following issue:
```
Validation failed: 
Missing required field: Name
Missing required field: Email
Missing required field: Phone
```

Is anyone able to help me understand why the admin panel seems to think this form is a required element on the `landing` page? It's actually a form to be displayed on the frontend page not within the edit of the page,
