### ISSUE TITLE
Cannot save page in AdminPanel

### ISSUE THREAD

**Issue by wepawetmose** [getgrav/grav-plugin-admin#172]
I have Admin Panel v.0.5.0 installed. And I created an user who should be able to change content of the pages. In my yaml file I have following lines:

```
access:
  admin:
    login: true
    pages: true
```

I can login into the Admin Panel and as expected only pages are shown, but if I edit something and try to save it. I get following message: You have insufficient permissions for task save.
I use Apache webserver.
