### ISSUE TITLE
Validation failed: Invalid input in "Content"

### ISSUE THREAD

**Issue by MaZyGer** [getgrav/grav-plugin-admin#1761]
![image](https://i.imgur.com/tm3whGl.png)
Version Grav v1.6.16 - Admin v1.9.10

As you can see in the image I get invalid input if I just paste the default text. I used "---" before and "-" between lines and after it (to test something) it started with this. For some reason it is working if I have only one paragraph (without new lines).. otherwise I get this error.

**EDIT**: I just realized it is happening to all my pages now. I cannot save changes anymore. Crazy. I did not change anything.. it just happens when I test "---" between new lines.

**EDIT2**: I found the problem but I don't know why I have that problem. I did not change anything. In my template in blueprints in default.yaml I had

```
title: default
'@extends':
    type: default
    
form:
    fields:
      content:
        fields:
          header.subheading:
            type: text
            label: test
            help: test

```
This did not made any problems before.. but suddently it did. I removed the file and is working again.
