### ISSUE TITLE
List field type not saving correctly

### ISSUE THREAD

**Issue by ricardo118** [getgrav/grav-plugin-admin#1774]
When using a type: array within a type: list such as

```
            header.compare:
              type: list
              label: Compare Sections
              btnLabel: Add Section
              style: vertical
              fields:
                .title:
                  type: text
                  label: Title of Section
                .items:
                  type: array
                  style: vertical
                  value_only: true
                  label: Compare Item
```

This causes new items added by the admin via the UI to show up like:

![image](https://i.imgur.com/BfK0p5l.png)

as you can see by the post ![image](https://i.imgur.com/0z845NC.png) this is most likely an issue with the js post generation
