### ISSUE TITLE
Pagemedia upload error when using mediapicker in the same page

### ISSUE THREAD

**Issue by buzatuAda** [getgrav/grav-plugin-admin#1782]
There is an issue I noticed while trying to upload pictures in an article with pagemedia and also using the mediapicker to choose those picture for different fields.

Steps to reproduce it:
1. Upload picture with pagemedia field. At this point everything goes ok, picture is uploaded successfully. The requested url is of the following form: **"http://localhost:8847/admin/media/leadership/7-hip-hop-songs-die-jeder-transformer-kennen-sollte.json/task:addmedia"**
2. Click on a field of type mediapicker and browse the pictures.
3. Try to upload another picture using the pagemedia field. Here the issue comes in place. The picture is not uploaded successfully. And by this i mean the picture gets uploaded but returns and error. The requested url is now of the following form: **"http://localhost:8847/admin/media-manager/leadership/7-hip-hop-songs-die-jeder-transformer-kennen-sollte.json/task:addmedia"**

The only workaround for now it was to make sure to upload everything before using the mediapicker.

Screenshots:
<img width="1128" alt="Screen Shot 2019-11-08 at 16 39 54" src="https://user-images.githubusercontent.com/52411474/68487093-2b458300-024b-11ea-98cc-2fee5afdf6fb.png">
<img width="1434" alt="Screen Shot 2019-11-08 at 16 39 37" src="https://user-images.githubusercontent.com/52411474/68487126-39939f00-024b-11ea-81d0-eff6bf1d3749.png">
<img width="1440" alt="Screen Shot 2019-11-08 at 16 39 44" src="https://user-images.githubusercontent.com/52411474/68487128-39939f00-024b-11ea-8d1f-2e2ec495e1ae.png">

**Comment by rhukster** [comment]
I do this frequently and have never noticed an issue.  Are there another plugins installed? Can you provide a copy of the custom blueprint and a page example?

**Comment by buzatuAda** [comment]
I have the following plugins installed 
- admin - 1.9.11
- email - 3.0.3
- form - 3.0.9
- login - 3.0.4
- login-oauth - 1.4.0
- git-sync - 2.0.5
- pagination - 1.4.2
- sitemap - 1.9.4
- breadcrumbs - 1.5.1
- admin-addon-user-manager - 2.1.8
- auto-date - 1.0.2
- tinymce-editor - 1.2.7
- readingtime - latest
- toc - 1.4.1
- feed- 1.7.1

this is the content of the custom blueprint:
```
title: ARTICLE_ADMIN_TAB_TITLE

'@extends':
    type: default
    context: blueprints://pages

form:
  validation: loose
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        content:
          type: tab
          title: PLUGIN_ADMIN.CONTENT
          fields:
            teaser_options:
              type: section
              title: 'Teaser options'
              underline: true
              fields:
                header.is_hero_with_picture:
                  type: toggle
                  label: ARTICLE_TEASER_HERO_TYPE
                  highlight: 1
                  default: 0
                  size: medium
                  options:
                    0: 'Hero with teaser text'
                    1: 'Hero picture with title'
                  validate:
                    type: bool
                header.teaser_headline_is_right:
                    type: toggle
                    label: ARTICLE_TEASER_HEADLINE_ALIGN
                    highlight: 1
                    default: 0
                    size: medium
                    options:
                      0: 'Left'
                      1: 'Right'
                    validate:
                      type: bool
                header.crop_picture_align:
                  type: select
                  size: small
                  label: ARTICLE_CROP_PICTURE_ALIGN
                  default: 'center-center'
                  options:
                    align-left-top: 'left-top'
                    align-left-center: 'left-center'
                    align-left-bottom: 'left-bottom'
                    align-center-top: 'center-top'
                    align-center-center: 'center-center'
                    align-center-bottom: 'center-bottom'
                    align-right-top: 'right-top'
                    align-right-center: 'right-center'
                    align-right-bottom: 'right-bottom'
                  validate:
                    type: string
            article_options:
              type: section
              title: 'Article content'
              underline: true
              fields:
                header.headline:
                    'ordering@': 1
                    type: text
                    label: ARTICLE_ADMIN_HEADLINE
                    style: vertical
                    default:
                    validate:
                      type: string
                      required: true
                      message: 'Validation: Required. Editors Headline.'
                    classes: charcount
                header.article_image:
                    'ordering@': 2
                    type: mediapicker
                    label: ARTICLE_ADMIN_IMAGE
                    preview_images: true
                    validate:
                      required: false
                      message: 'Validation: Required. Article Image.'
                    accept:
                      - .png
                      - .PNG
                      - .jpg
                      - .jpeg
                header.article_image_caption:
                    'ordering@': 3
                    type: text
                    label: ARTICLE_ADMIN_CAPTION
                    default:
                    validate:
                      type: string
                      required: false
                      message: 'Validation: Required. Caption for article image.'
                    classes: charcount
                header.article_video:
                  'ordering@': 4
                  type: text
                  label: ARTICLE_ADMIN_VIDEO
                  default:
                  validate:
                    type: string
                    pattern: '^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$'
                    required: false
                    message: 'Validation: If present it must be a valid URL'
                header.content_type:
                    'ordering@': 5
                    type: select
                    label:  ARTICLE_ADMIN_CONTENT_TYPE
                    size: small
                    options:
                      default:
                      Analyse:  ARTICLE_ADMIN_CONTENT_ANALYSE
                      Kommentar:  ARTICLE_ADMIN_CONTENT_KOMMENTAR
                      Studie:  ARTICLE_ADMIN_CONTENT_STUDIE
                      Interview:  ARTICLE_ADMIN_CONTENT_INTERVIEW
                header.teaser_text:
                    'ordering@': 6
                    type: textarea
                    label: ARTICLE_ADMIN_TEASER_TEXT
                    autofocus: false
                    style: vertical
                    validate:
                      pattern: '.{1,400}'
                      message: 'Validation: Required. Teaser text field can contain max 400 characters.'
                      required: true
                    classes: charcount
                header.readingtime:
                    'ordering@': 7
                    type: text
                    label: ARTICLE_ADMIN_READING_TIME
                    autofocus: false
                    style: vertical
                header.article_author_list:
                  'ordering@': 10
                  name: composed_author_list
                  type: list
                  style: vertical
                  label: 'Add author to the author list:'
                  min: 1
                  classes: editors-choice
                  validate:
                    required: true
                    message: 'Add an author.'
                  fields:
                    .articleauthor:
                      type: select
                      size: medium
                      classes: fancy
                      label: ARTICLE_ADMIN_AUTHOR
                      style: vertical
                      config-default@: ''
                      data-options@: '\Grav\Plugin\Transformation\TransformationUtils::getAuthorsList'
                      validate:
                        required: true
                        message: 'Add a valid author.'
        options:
            type: tab
            title: PLUGIN_ADMIN.OPTIONS
            fields:
              publishing:
                type: section
                title: PLUGIN_ADMIN.PUBLISHING
                underline: true
                fields:
                  header.exclusive:
                      'ordering@': 1
                      type: toggle
                      label: ARTICLE_ADMIN_EXCLUSIVE
                      highlight: 1
                      default: 0
                      size: medium
                      options:
                        1: PLUGIN_ADMIN.YES
                        0: PLUGIN_ADMIN.NO
                      validate:
                        type: bool
        advanced:
                  type: tab
                  title: PLUGIN_ADMIN.ADVANCED

                  fields:
                    columns:
                      type: columns
                      fields:
                        column1:
                          type: column
                          fields:
      
                            folder:
                              type: text
                              label: PLUGIN_ADMIN.FOLDER_NAME
                              readonly: true
                              validate:
                                rule: slug


```
