### ISSUE TITLE
File field inside list doesn't show uploaded image after save

### ISSUE THREAD

**Issue by anisiearadis** [getgrav/grav-plugin-admin#1797]
Hey,

I have the following config blueprint in `user/blueprints/config/company.yaml`:

```yaml
title: Company

form:
  validation: loose
  fields:

    # ... some other definitions removed for simplicity

    partners:
      type: section
      title: Partners
      underline: true

      fields:
        partners:
          type: list
          style: vertical
          fields:
            .company_name:
              type: text
              label: Company Name
            .company_logo:
              type: file
              label: Company Logo
              destination: 'user/themes/my-theme/assets/images'
              multiple: false
              accept:
                - image/jpeg
                - image/png

```

This works really great. I can easily add a new item, enter the name of the company and add an image to the list item. Then I save my settings. The image is uploaded to the given path and I get the following YAML inside `user/config/company.yaml`:

```yaml

# ... some other settings removed for simplicity

partners:
  -
    company_name: 'Company A'
    company_logo:
      user/themes/my-theme/assets/images/company-a.jpg:
        name: company-a.jpg
        type: image/jpeg
        size: 16042
        path: user/themes/my-theme/assets/images/company-a.jpg
  -
    company_name: 'Company B'
    company_logo:
      user/themes/my-theme/assets/images/company-b.png:
        name: company-b.png
        type: image/png
        size: 25768
        path: user/themes/my-theme/assets/images/company-b.png
  -
    company_name: 'Company C'
    company_logo:
      user/themes/my-theme/assets/images/company-c.png:
        name: company-c.png
        type: image/png
        size: 20995
        path: user/themes/my-theme/assets/images/company-c.png

```

After the POST finished and the page reloads the images doesn't get shown. The text fields are filled properly. I'm not sure if that is a duplicate of [#1786](https://github.com/getgrav/grav-plugin-admin/issues/1786), because I don't use a fieldset in my example.
