### ISSUE TITLE
Uploaded file in custom file upload field not written in header.

### ISSUE THREAD

**Issue by localnetwork** [getgrav/grav-plugin-admin#1871]
Admin Panel Version: v1.10.0-rc.8

YAML File

```yaml
extends@: default

form:
  fields:
    tabs:
      fields:
        content:
          type: tab
          title: PLUGIN_ADMIN.CONTENT

          fields:
            xss_check:
              type: xss

            header.title:
              type: text
              autofocus: true
              style: vertical
              label: PLUGIN_ADMIN.TITLE

            content:
                type: markdown
                validate:
                  type: textarea

            header.media_order:
              type: pagemedia
              label: PLUGIN_ADMIN.PAGE_MEDIA
            header.custom_file:
              type: file
              label: A Label
              multiple: false
              destination: 'self@'
              random_name: false
              avoid_overwriting: false
              limit: 10
              accept:
                - image/*
```

Result after saving content
`title: test
custom_file: {  }
media_order: user-edit-1.png
`

See video here: https://drive.google.com/file/d/1SHT_08AHrLc_zrxK1cJUDU1m0ooU2c0t/view
