### ISSUE TITLE
Filepicker is not saving the list of files after saving the page

### ISSUE THREAD

**Issue by arkhi** [getgrav/grav-plugin-admin#1903]
I encountered this issue on a project and couldn’t get anything to work after testing there, so I followed these steps with [this environment][3]:

1. Download [latest Grav + Admin plugin][1];
1. Create a [Vagrant Box based on Ubuntu 20.04][2] (attached files are placed at the root of the Grav files);
1. Modify user/themes/quark/blueprints/default.yaml with the following:
    ```yaml
    extends@: default

    form:
      fields:
        tabs:
          fields:
            content:
              fields:
                header.media_selected:
                  type: filepicker
                  folder: '@self'
                  preview_images: true
                  multiple: true
                  label: Pick some files

            advanced:
              fields:
                columns:
                  fields:
                    column1:
                       fields:
                         header.body_classes:
                           markdown: true
                           description: 'Available classes in Quark Theme (space separated):<br />`header-fixed`, `header-animated`, `header-dark`, `header-transparent`, `sticky-footer`'
    ```
1. Upload three images at http://192.168.20.2/admin/pages/home
1. Select one of the files (or both).
1. Save.

- No files are presented in the `media_selected` filepicker.
- The user/pages/01.home/default.md file has the following frontmatter:
    ```yaml
    ---
    title: Home
    media_order: '011-000228520031.jpg,036-000228520018-02.jpg,061-000228520006.jpg'
    media_selected: ''
    body_classes: 'title-center title-h1h2'
    ---
    ```

---

I tried to save with <kbd>Ctrl</kbd>+<kbd>s</kbd> or clicking the `Save` button, with a different number of images, and did not see anything in the Firefox dev tools’ Console or Network errors, which makes me think it could be a PHP issue more than anything frontend.

I hope I’m not missing something; let me know if I can be of any more assistance, thanks!

This issue might be related to #1441 and #1580.

[1]: https://getgrav.org/download/core/grav-admin/1.6.26
[2]: https://github.com/getgrav/grav-plugin-admin/files/4771054/vagrant-files.zip
[3]: https://www.whatsmybrowser.org/b/NC1FC
