### ISSUE TITLE
New string in language file needed

### ISSUE THREAD

**Issue by dimayakovlev** [getgrav/grav-plugin-admin#191]
PLUGIN_STATUS - label for "enabled" plugin field.
```
en:
  PLUGIN_STATUS: 'Plugin status'

ru:
  PLUGIN_STATUS: 'Статус плагина'
```
