### ISSUE TITLE
Save failed usign file upload field

### ISSUE THREAD

**Issue by Jakub-Nagy** [getgrav/grav-plugin-admin#1920]
Hi,
I'm using file upload fields in multiple of my forms. Everything worked well until I updated to version Grav 1.7.0rc.13 - Admin 1.10.0rc.13. Now I get this when trying to save an uploaded file:

> Save Failed: Cannot unset nested property header custom_file selector_vsetci.svg on non-array value

The blueprint for this specific form field looks like this: 
`
header.custom_file:
                  type: file
                  label: PLUGIN_ADMIN.IMAGE
                  multiple: false
                  destination: 'self@'
                  filesize: 5
                  accept:
                    - image/*
`

There seems to be an issue with the file upload field being nested inside the header. When I remove the "header." and leave just "custom_file" then it's possible to save the form but the file path doesn't actually save anywhere.

Is this a compatibility issue? As I said before, it worked with the earlier versions of Grav and Admin Plugin.

**Comment by rhukster** [comment]
can i please see the full page .md file in a code block so i can recreate exactly?

**Comment by Jakub-Nagy** [comment]
Alright. This is the whole blueprint for the page I want to edit:

```yaml
title: Default text
form:
  fields:
    tabs: 
      type: tabs
      active: 1
      fields:
        content:
          type: tab
          title: PLUGIN_ADMIN.CONTENT
          fields:
            xss_check:
              type: xss
            header.title:
              type: text
              label: Názov stránky
            content:
              type: markdown
            header.media_order:
              type: pagemedia
              label: PLUGIN_ADMIN.PAGE_MEDIA
        options:
          type: tab
          title: PLUGIN_ADMIN.OPTIONS
          fields:
            advanced:
              type: section
              title: PLUGIN_ADMIN.ADVANCED
              underline: true
              fields:
                header.custom_file:
                  type: file
                  label: PLUGIN_ADMIN.IMAGE
                  multiple: false
                  destination: 'self@'
                  filesize: 5
                  accept:
                    - image/*
                header.sidebar:
                  type: toggle
                  label: Sidebar
                  default: 1
                  highlight: 1
                  options:
                    1: PLUGIN_ADMIN.YES
                    0: PLUGIN_ADMIN.NO
                  validate:
                    type: bool
                header.date:
                  type: datetime
                  label: PLUGIN_ADMIN.DATE
                header.modules:
                  type: list
                  label: Externé moduly
                  btnLabel: Pridať modul
                  fields:
                    .type:
                      type: toggle
                      label: Poloha modulu
                      default: external
                      highlight: external
                      options:
                        internal: Vnúri obsahu
                        external: Za obsahom
                    .module:
                      type: pages
                      label: Výber modulu
                      show_all: true    
                      default: none 
                      options:
                        none: Žiadny modul       
                    .template:
                      type: select
                      classes: fancy
                      label: PLUGIN_ADMIN.DISPLAY_TEMPLATE
                      default: none 
                      options:
                        none: Žiadna šablóna
                      data-options@: '\Grav\Plugin\AdminPlugin::pagesModularTypes'  
            blueprint:
              type: blueprint
```

And this is the markdown:
```markdown
---
title: 'Ochrana osobných údajov'
sidebar: '1'
body_classes: ''
order_by: ''
order_manual: ''
custom_file:
    user/pages/10.ochrana-osobnych-udajov/selector_vsetci.svg:
        name: selector_vsetci.svg
        type: image/svg+xml
        size: 10833
        path: user/pages/10.ochrana-osobnych-udajov/selector_vsetci.svg
---

Dodržiavame právne predpisy týkajúce sa ochrany osobných údajov, najmä Všeobecného nariadenia o ochrane údajov (Nariadenie (EÚ) 2016/679) („GDPR“) a zákona č. 18/2018 Z. z. o ochrane osobných údajov v platnom znení („ZZOÚ“).

### Kto je zodpovedný za spracovanie osobných údajov?

Prevádzkovateľom pri spracovaní vašich osobných údajov je:
```

When I load the page, the preview for the image displays fine. The problem is when I try to delete the image, add a new one and save the page.
