### ISSUE TITLE
Validation of required fields causes Runtime Error

### ISSUE THREAD

**Issue by kayvieider** [getgrav/grav-plugin-admin#1939]
Grav v1.6.26 - Admin v1.9.15

When I set filepicker, date or also other fields in blueprint with `validate.required: true` and leave them empty in the admin panel is causes a Runtime Error after hitting the save button:

![image](https://user-images.githubusercontent.com/64414721/89283527-98a50980-d64d-11ea-9615-746f7dbff953.png)

But in this case the file "text.html.twig" exists despite the error claims otherwise. Setting `validate.required: false` makes the error disappear. This error exists only appears on modular pages.

Relevant blueprint code:
``` yaml
header.img:
  type: filepicker
  label: Logo
  preview_images: true
  accept:
     - .jpg
     - .png
  validate:
    required: true
```
