### ISSUE TITLE
File upload does not work in fieldset and list type

### ISSUE THREAD

**Issue by ElGecko76** [getgrav/grav-plugin-admin#1944]
Hi, I get this error when I upload an image on admin yet the image does not have specials characters:

> Bad filename error

To reproduce this error, it is necessary to add `article.yaml` file in `user/themes/your_theme/blueprints` and put this code:

```
title: Article
'@extends':
    type: default
    context: blueprints://pages

form:
    fields:
        tabs:
            type: tabs
            active: 1

            fields:
                content:
                    type: tab
                    fields:
                        content:
                            unset@: true

                        header.article:
                            ordering@: +2
                            type: fieldset
                            title: Article
                            icon: square
                            collapsed: false
                            collapsible: true
                            fields:
                                .image:
                                    type: file
                                    label: Image principale
                                    random_name: true
                                    multiple: false
                                    destination: 'user/themes/project/images/uploads'
                                    autofocus: false
                                    accept:
                                        - image/*
```

If we remove the fieldset, it works:

```
title: Article
'@extends':
    type: default
    context: blueprints://pages

form:
    fields:
        tabs:
            type: tabs
            active: 1

            fields:
                content:
                    type: tab
                    fields:
                        content:
                            unset@: true

                        header.article.image:
                            type: file
                            label: Image principale
                            random_name: true
                            multiple: false
                            destination: 'user/themes/project/images/uploads'
                            autofocus: false
                            accept:
                                - image/*
```

But if we add this on file type and we upload an image, it's not possible to submit the form:

```
validate:
    required: true
```

These problems are the same if we use a `list` type instead of `fieldset` as parent of `file` type.
