### ISSUE TITLE
Pagemedia: order of images is not displayed corectlly in admin

### ISSUE THREAD

**Issue by mahish** [getgrav/grav-plugin-admin#1947]
Versions: Grav 1.6.27, Admin 1.9.16, Form v4.1.1, Admin Addon Media Metadata v1.1.0

The `pagemedia` form field in admin does not display images in the right order. To reproduce the issue:

1. order images in `pagemedia` form field
2. save the page
3. order of images in `pagemedia` in admin is wrong (is not same as it is in frontmatter)
4. order of images on webpage is ok

Please see the short video: https://gyazo.com/6d203c7341c80e30fda131b2a69f35a9 

My blueprint looks like this:
```yaml
title: Artist

form:
  validation: loose

  fields:

    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab
          title: PLUGIN_ADMIN.CONTENT

          fields:

            header.title:
              type: text
              autofocus: true
              style: vertical
              label: NAME

            content:
              type: markdown
              label: ABOUT_THE_ARTIST
              style: vertical
              validate:
                type: textarea

            header.cv:
              type: markdown
              label: CV
              style: vertical
              validate:
                type: textarea

            header.fieldsetPhotos:
              type: fieldset
              title: Photos
              # help: Help text
              info: Upload photos here. Order them via drag'n'drop.
              # text: Text inside fieldset and before other fields
              # icon: comments       # Fork Awesome icons system (see : forkaweso.me).
              collapsed: false     # Initial state of fieldset (see collapsible option)
              collapsible: true    # Whether one can expand the fieldset or not
              fields:
                header.photos:
                  type: pagemedia
                  style: vertical
                  # label: Photos
                  destination: '@self'
                  multiple: true
                  limit: 0
                  filesize: 2
                  accept:
                    - image/*


        advanced:
          type: tab
          title: PLUGIN_ADMIN.ADVANCED
          import@:
            type: blueprints/partials/advanced-directory
            context: theme://

        aura:
          type: tab
          title: SEO (Aura plugin)
          import@:
            type: blueprints/partials/aura
            context: theme://
```

**Comment by mahagr** [comment]
That doesn't look like a page blueprint?

**Comment by mahish** [comment]
@mahagr why do you think so? what is wrong with that? I dont extend `default`. For `advanced` tab I use only some parts I really need. Is that problem?

**Comment by mahish** [comment]
I switched off following plugins: Admin Addon Media Metadata v1.1.0, Aura v2.0.1. 
I also modified the blueprint to extend default one to be more standard. But the problem is still there:(

```yaml
title: Artist
'@extends':
    type: default
    context: blueprints://pages

form:
  validation: loose

  fields:

    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab
          title: PLUGIN_ADMIN.CONTENT

          fields:

            header.title:
              type: text
              autofocus: true
              style: vertical
              label: NAME

            content:
              type: markdown
              label: ABOUT_THE_ARTIST
              style: vertical
              validate:
                type: textarea

            header.media_order:
              unset@: true

            header.cv:
              type: markdown
              label: CV
              style: vertical
              validate:
                type: textarea

            photos:
              type: fieldset
              title: Photos
              # help: Help text
              info: Upload photos here. Order them via drag'n'drop.
              # text: Text inside fieldset and before other fields
              # icon: comments       # Fork Awesome icons system (see : forkaweso.me).
              collapsed: false     # Initial state of fieldset (see collapsible option)
              collapsible: true    # Whether one can expand the fieldset or not
              fields:
                header.photos:
                  type: pagemedia
                  style: vertical
                  # label: Photos
                  destination: '@self'
                  multiple: true
                  limit: 0
                  filesize: 2
                  accept:
                    - image/*
```
