### ISSUE TITLE
Unable to save module when entering URLs in text fields (self-made blueprint) 1.6.28

### ISSUE THREAD

**Issue by d0nh** [getgrav/grav-plugin-admin#1961]
I have a self-made theme with a modular page that had been working perfectly fine until today after I updated to 1.6.28 (I think I was on quite a recent version before, likely the last one).

The problem: If I enter some URLs in the "header.links.url" field, the entire module can't be saved anymore. Instead, saving (either via Ctrl + S or the Save button) **opens the "download your HTML page" window** which I would get if I pressed Ctrl + S anywhere else in the Internet instead of saving the site. If I cancel this, the saving option is disabled until I reload the page.
Especially weird about this is that I'm unable to find out what kind of URLs cause this. I reduced a version of my module to only the URL problem and tried some facebook / soundcloud / youtube and other URLs. Some worked, others didn't. As mentioned before, in earlier GRAV versions this has never happened.

An example URL that allowed me to save the module: https://facebook.com
An example that didn't allow me to do so: https://www.facebook.com/watch/?v=1273730996162103

Here's my yaml:

```yaml
title: Personen-Portrait
extends@: default

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            header.linkedimg:
              type: text
              label: Alternativ hier ein externes Bild verlinken
            header.links:
              type: list
              style: vertical
              label: Links oder Angaben zur Person
              fields:
                .icon:
                  type: filepicker
                  folder: 'theme@:/images/icons'
                  label: Icon
                  preview_images: true
                  accept:
                    - .png
                    - .jpg
                    - .svg
                .text:
                  type: text
                  label: Link-Text
                .url:
                  type: text
                  label: Link-URL
                .file:
                  type: filepicker
                  label: Download
                  folder: @self`
```
