### ISSUE TITLE
Problem with `config-default@` and setting a value

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav-plugin-admin#1971]
This relates to blueprints and probably Grav 1.7/Admin 1.10.

I have a custom page blueprint definition with a field:

```
header.hero.height:
          toggleable: true
          type: text
          label: Height Classes
          config-default@: theme.hero.height
```

When there is no value it saves fine (i.e. not toggled on).  As soon as I provide a value in the field and save it gives me an error:

```
Save Failed: Undefined index: type
```

Removing the `config-default@` allows saving just fine, so it's definitely related to that.  Also, make no difference if I change it to `config-placeholder@`, still gives error on save.
