### ISSUE TITLE
Hard refresh on some page causes admin session to be invalidated

### ISSUE THREAD

**Issue by stphane** [getgrav/grav-plugin-admin#1980]
### Scenario:

» I log into the administration panel.  
» I open a new tab and go to the website homepage and hit <kbd>Ctrl</kbd>+<kbd>F5</kbd>.  
» I get back to the administration panel's tab and try to navigate anywhere in the admin section  
⇒ I get redirected to the administration login page. (I can see the session token has changed)  

### Context:

Website is exposed as a sub-directory : `https://foo.com/blog`.  
The admin panel is accessible via a custom root `/manage` (`https://foo.com/blog/manage`).

» Using PHP/Redis session handler
```ini
php_admin_value[session.save_handler] = redis
php_admin_flag[session.cookie_secure] = true
```
» user/config/system.yaml
```yaml
custom_base_url: /blog
# ...
session:
  enabled: true
  initialize: true
  timeout: 1800
  name: grav-site
  uniqueness: path
  secure: true
  httponly: true
  split: true
  path: /blog/
```

_Has probably nothing to do with the browser ... anyway:_  
Firefox 84.0b3 (64-bit) ; Google Chrome Version 83.0.4103.116
