### ISSUE TITLE
Range inside a list shows no value in screen when adding a new page

### ISSUE THREAD

**Issue by javiercoll** [getgrav/grav-plugin-admin#2062]
Grav version: 1.7.5
Admin Panel version: 1.10.3

How to reproduce:

1. Add this blueprint:
```
title: Test

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        test:
          type: tab
          title: Test

          fields:
            header.thisworks:
              name: thisworks
              type: range
              label: Range outside list
              default: 0
              validate:
                min: 0
                max: 10

            header.thisdoesnot:
              name: test
              type: list
              label: List

              fields:
                .range:
                  name: range
                  type: range
                  label: Range in list
                  default: 0
                  validate:
                    min: 0
                    max: 10
```
2. Go to Admin > Pages > Add page, and add a page with the previous template
3. In the 'List' list, click on 'Add item'
4. In the 'Range in list' range, move the range.

Current behavior:
The range value does not change.

Expected behavior:
The range value changes according to the range.

Additional information:
Even though the range value is not updated in the UI, once you save it's populated correctly. Also, when you edit the page again, the range works as expected. It's just not working for new pages.

If you have a range outside of a list, the range works as expected.
