### ISSUE TITLE
filepicker does not work anymore – no dropdown, no preview

### ISSUE THREAD

**Issue by d0nh** [getgrav/grav-plugin-admin#2071]
I made a custom theme. It has worked for around 1.5 years now with this exact configuration. Today I updated to Grav 1.7.5 (also updated all plugins) and now filepickers do not work anymore when I'm trying to edit my pages.
I can't select files and the "Available" dropdown also doesn't appear. Manually entering a file name leads to the picker field being emptied as soon as I save or move the cursor away. The issue is not present on older Grav 1.6.X projects I am running (with the exact same yaml code).
 
Blueprint config, only the filepicker part:

```yaml
              fields:                                                           
                .icon:                                                          
                  type: filepicker                                              
                  folder: 'theme@:/images/icons'                                
                  label: Icon                                                   
                  preview_images: true                                          
                  accept:                                                       
                    - .png                                                      
                    - .jpg                                                      
                    - .svg                                                     `
```

(Please excuse me as I have no clue how to properly insert code in GitHub. I'm still new to development. I don't know how to insert line breaks. It was properly formatted in the .yaml.)
The zipped yaml is attached. 
[yaml.zip](https://github.com/getgrav/grav-plugin-admin/files/5989814/yaml.zip)
