### ISSUE TITLE
ACL system is broken

### ISSUE THREAD

**Issue by Karmalakas** [getgrav/grav-plugin-admin#2073]
Latest fresh Grav 1.7.6 + Admin ZIP package installed

I think there's something wrong with ACL system. I have a group with these permissions:
![image](https://user-images.githubusercontent.com/3602819/108340086-ded44b80-71e0-11eb-986c-7a3fd95a1564.png)

And when I login with user (with this group assigned) and go to _Pages_, I get 404 page does not exist. If I mark _Allowed_ on all _Pages_ section in a group permissions, then _Pages_ link in left sidebar menu completely disappears

If I mark at least one, but not all permissions under _Pages_, then menu item appears with label of `0` pages. Even it has these 2 default pages (which I see with my main admin user)

Same behavior with _User Accounts_ permission section. If all enabled, menu link disappears. If at least one permission disabled, menu is there with label `0` and navigating to it gives a 404 error

Same happens when permissions assigned directly to an account and not via a group
Tried changing Flex Objects permissions, but didn't help
With _Super User_ enabled I can access everything then

Seems like it's broken only with flex objects (pages, accounts)

IMO this should be addressed ASAP

**Comment by mahagr** [comment]
You are denying Flex Objects and deny always wins if you have both Allow and Deny. Please do not use deny rules unless if the goal is to always prevent the user from accessing an asset.

**Comment by Karmalakas** [comment]
As I said, I've tried with Flex Objects enabled, but same thing

**Comment by mahagr** [comment]
Can you pass the access section from the `config/groups.yaml` for that group?

**Comment by Karmalakas** [comment]
Now I have everything _Not set_ except what I want for user to access
```yaml
Editor:
  access:
    admin:
      login: true
      cache: true
      pages:
        create: true
        read: true
        update: true
        list: true
      plugins: true
  enabled: true
```
