### ISSUE TITLE
Image path not saved

### ISSUE THREAD

**Issue by marymidori** [getgrav/grav-plugin-admin#2086]
When uploading images to a Page, the path is no longer saved.  The image is uploaded into the page directory but the reference to that directory is not saved.

For example it now saves this :+1: 
```
photo:
  IMG_4141.JPG:
    name: IMG_4141.JPG
    type: image/jpeg
    size: 474122
    path: IMG_4141.JPG
```

Instead of this :

```
photo:
  user/pages/03.penser-le-paysage/IMG_4141.JPG:
    name: IMG_4141.JPG
    type: image/jpeg
    size: 474122
    path: user/pages/03.penser-le-paysage/IMG_4141.JPG
```

This issue arrived after updating from v1.5 to v1.7 and with the most recent Admin Plugin v1.10.6.

Thanks
