### ISSUE TITLE
Cannot translate page / add new page of different language

### ISSUE THREAD

**Issue by dexterxx-pl** [getgrav/grav-plugin-admin#2160]
### Issue
I can't create new page with translation for existing page. Trying to edit admin panel shows (1):
> This page has not been translated to  English language yet! Falling back to Polski language.

The language switcher on editing page (it is language switcher?) does nothing (2).

![grav issue](https://img.dexterxx.pl/i/81b4bd.jpg)

Whatever which not yet translated language I'm gonna choose in drop-menu there's same behaviour.

![grav issue](https://img.dexterxx.pl/i/c7397f.jpg)

### Reproduce

1. Enable multilang 
2. Create new page on your context - whatever it finally would be the "default" language or first supported
3. Try to edit translation page (any red dot in second screenshot)

or

1. Edit any page with only one translation
2. Play with language URL section of that page:
   * http://localhost/en/admin/pages/home
   * http://localhost/pl/admin/pages/home
   * http://localhost/XY/admin/pages/home

### Config

```
languages:
  supported:
    - pl
    - en
  default_lang: pl
  include_default_lang: true
  include_default_lang_file_extension: false
  translations: true
  translations_fallback: true
  session_store_active: false
  http_accept_language: false
  override_locale: false
  pages_fallback_only: false
```

### Admin account config
```
language: en
content_editor: default
```

### Admin plugin conf
```
route: '/somewhere'
```

### What I tried

1. Change user context / relogin -- same issue
2. Playing with almost all settings from `languages` section.

### Workaround

Manually create file for specified translation eg. `default.en.md`. After that you can edit both languages.

Could not find workaround without server access / using Admin panel.

### Some more info

1. Looks like admin panel improperly failing back with language - should allow to create file if it not exists for specified language
2. Even if I have two files `default.md` and `default.en.md` the default file is in lang switcher interpreted as first language (Polish) - cannot choose "default" instead of first language. That should be also fixed IMO - to be able to manage default language in case having more than overall two.

### Versions

Grav: latest 1.7.17
Grav admin: latest 1.10.17
