### ISSUE TITLE
Missing data in list fields

### ISSUE THREAD

**Issue by PraserX** [getgrav/grav-plugin-admin#2187]
Hi, I've just realized that data are missing in all list fields at admin interface. Is it only issue for me? Or did something wrong during update?

Thanks.

![screenshot](https://user-images.githubusercontent.com/24474722/136019011-897d47fd-b7a7-45a0-a285-be49e97d84c5.png)

**Comment by mahagr** [comment]
I cannot reproduce the issue. Are you all up to date? Which plugins/theme do you have installed?

**Comment by PraserX** [comment]
I have similar issue when using fieldset from blueprint reference example. The content of fieldset is empty.

```yaml
header.fieldset:
  type: fieldset
  title: Your title
  help: Help text
  info: Info text
  text: Text inside fieldset and before other fields
  icon: comments       # Fork Awesome icons system (see : forkaweso.me).
  collapsed: true      # Initial state of fieldset (see collapsible option)
  collapsible: true    # Whether one can expand the fieldset or not
  fields:
    header.fieldset.an_example_text:
      type: text
      label: text
    header.fieldset.an_example_textarea:
      type: textarea
      label: textarea
```

![Screenshot 2021-10-06 at 14-16-08 Šablona Portal Neveřejný web](https://user-images.githubusercontent.com/24474722/136200529-860a176e-963d-4b64-b9c5-7d5d4461f606.png)
