### ISSUE TITLE
select option group name ignores language strings

### ISSUE THREAD

**Issue by dani-ooo** [getgrav/grav-plugin-admin#2203]
when naming option groups with a language string, either as `select` or `select_optgroup`, it’s not displayed as it should.

```yaml
form.field:
  label: THEME_X.LABEL
  type: select
  options:
    - THEME_X.SELECT_GROUP:
      - THEME_X.SELECT_OPTION1
```
in the example above, `THEME_X.SELECT_OPTION1` uses the corresponding language string, as expected, but `THEME_X.SELECT_GROUP` appears exactly as “THEME_X.SELECT_GROUP”. needless to say i made sure the string was in the theme’s `languages.yaml`.
