### ISSUE TITLE
select option group options don’t take keys

### ISSUE THREAD

**Issue by dani-ooo** [getgrav/grav-plugin-admin#2204]
select options don’t work when entering `key: value` formatting, either as `select` or `select_optgroup` fields. i’ve attempted multiple ways, but it doesn’t work.

the following renders the select field without any options:
```yaml
form.field:
  type: select
  options:
    - select_group:
      option_value: "option key"
```

and this other option throws an error:
```yaml
form.field:
  type: select
  options:
    - select_group:
      - option_value: "option key"
```
_An exception has been thrown during the rendering of a template ("Array to string conversion")._
