### ISSUE TITLE
selectize options ignore language strings

### ISSUE THREAD

**Issue by dani-ooo** [getgrav/grav-plugin-admin#2205]
when naming selectize options with a language string, it’s not displayed as it should.

in this example, `THEME_X.SELECT_OPTION1` doesn’t render the corresponding string from the `languages.yaml` file, instead it appears exactly as “THEME_X.SELECT_OPTION1”.
```yaml
form.field:
  type: selectize
  selectize:
    options:
      - text: THEME_X.SELECT_OPTION1
        value: option1
```

needless to say i made sure the string was in the theme’s `languages.yaml`.
