### ISSUE TITLE
Bug: Fieldsets/sections and toggles within a list

### ISSUE THREAD

**Issue by m-schmale** [getgrav/grav-plugin-admin#2217]
Hi,

Unfortunately, there seems to be a bug with fieldsets/sections and toggles within a list.

If I go into expert mode and remove:

```
margin:
  marginTop: 0
  ...
```

then switch to normal mode, the checkboxes are not selected. But as soon as I tick a checkbox in this fieldset and press save, all fields in this fieldset are selected. Not just the one I ticked.

The same problem exists for sections. I've tried to replace fieldsets with sections, but this did not help.

Regards & happy New Year,
Mark

**Blueprint:**

```
title: Section
extends@:
  type: modular
  context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        layout:
          type: tab
          title: Layout

          fields:
            header.section:
              name: section
              type: section
              title: Sektion
              underline: true
              classes: layout

              fields:
                .rows:
                  name: rows
                  type: list
                  style: vertical
                  label: Reihen
                  collapsed: true
                  btnLabel: Neue Reihe

                  fields:
                    .margin:
                      name: margin
                      type: fieldset
                      title: Außenabstände
                      collapsed: true
                      collapsible: true

                      fields:
                        .marginTop:
                          type: range
                          label: Oben
                          validate:
                            min: 0
                            max: 5
                          toggleable: true
                        .marginRight:
                          type: range
                          label: Rechts
                          validate:
                            min: 0
                            max: 5
                          toggleable: true
```
