### ISSUE TITLE
Elements Field "works" only once - Grav v1.7.30 - Admin v1.10.30.2

### ISSUE THREAD

**Issue by FrancoisCapon** [getgrav/grav-plugin-admin#2238]
Hi,

I'm trying the Elements Field :
- at the first usage the good data are regsitred

` headers` 
```yaml
---
title: 'Elements Field'
elementsfieldone: stringfield
numberfield:
    number: ''
stringfield:
    string: 'Hello world!'
---
```
-  but after I can't change the value in the selected field nor register the value from the other field

` blueprint` 
```yaml
title: ElementsField

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab
          title: "Content"

          fields:
            header.elementsfieldone:
              type: elements
              label: Elements Field
              size: small
              options:
                numberfield: Number
                stringfield: String
              fields:
                numberfield:
                  type: element
                  fields:
                    .number:
                      type: text
                      size: small
                      label: Number
                stringfield:
                  type: element
                  fields:
                    .string:
                      type: text
                      size: small
                      label: String
```
Same behavior with the [Elements Field example](https://learn.getgrav.org/17/forms/blueprints/fields-available#elements-field)

Do I some configuration mistake or is it a bug :question:
