### ISSUE TITLE
Inconsistent default value/behaviour between select-one and select-multiple

### ISSUE THREAD

**Issue by hughbris** [getgrav/grav-plugin-admin#2253]
I noticed after setting a select single value and select multiple in my blueprints that the single one would default to the first option displayed. Simplified below (I am using those commented out functions, but the options and behaviour are the same):

```yaml
            header.cuisine:
              type: select
              label: Cuisine
              # data-options@: ['\Grav\Theme\Gravory::controlledVocabulary', 'cuisine']
              options:
                moroccan: 'Moroccan'
                italian: 'Italian'
                spanish: 'Spanish'

            header.diets:
              type: select
              label: Diet(s)
              multiple: true
              # data-options@: ['\Grav\Theme\Gravory::controlledVocabulary', 'diet']
              options:
                vegetarian: 'Vegetarian'
                vegan: 'Vegan'
                gluten-free: 'Gluten free'
              validate:
                type: array
```
The default value is the first option for the _single select field only_ and there's no way for a normal user to unset it:

![image](https://user-images.githubusercontent.com/288202/158289411-412689ba-75bb-4a0f-b29d-340b3659f23a.png)

I found a hack, which I am pleasantly surprised works, though I think it's less than optimal:

```yaml
              options:
                '': non-specific
                moroccan: 'Moroccan'
                italian: 'Italian'
                spanish: 'Spanish'
```

![image](https://user-images.githubusercontent.com/288202/158289699-f0e7c9ab-5867-41aa-976f-654a6bc917a0.png)

Note the feint placeholder text, and also no header is saved, which is good. If this hack is intended behaviour, let's document it.

**Comment by dani-ooo** [comment]
i’ve achieved it this other way:
```yaml
 header.cuisine:
  type: select
  label: Cuisine
  placeholder: non-specific
  default: null
  options:
    moroccan: 'Moroccan'
    italian: 'Italian'
    spanish: 'Spanish'
```
