### ISSUE TITLE
config.system.session.options overwriting

### ISSUE THREAD

**Issue by pboguslawski** [getgrav/grav-plugin-admin#2270]
When one configures manually session options in system.yaml i.e.
```
session:
[...]
  options:
    cache_limiter: private
```
like in

https://github.com/getgrav/grav/issues/1081#issuecomment-377124103

then saving configuration in admin resets it to
```
session:
[...]
  options:
    cache_limiter: null
```
and Grav still inserts
```
Pragma: no-cache
```
in frontend responses when sessions are enabled (required for forms to work) which makes cache headers (Expires, Cache-Control) for Grav pages useless.

Admin plugin should recognize and preserve session.options to allow Grav page caching tuning even for sessions.
