### ISSUE TITLE
dot in blueprint key

### ISSUE THREAD

**Issue by dani-ooo** [getgrav/grav-plugin-admin#2280]
i’m making a blueprint for collections for `@page.page`s only, as a `list` field like so:
```yaml
header.content.items:
  type: list
  fields:
    .@page.page:
      type: pages
```
 but this produces:
```yaml
content:
  items:
    -
      '@page':
        page:
          - /slug
```
which then doesn’t work for the templates.

i’ve tried different ways of escaping it, getting different results, but none of them working. a couple of examples:
- `.'@page.page'`:

```yaml
content:
  items:
    -
      '''@page':
        'page''':
          - /slug
```
- [`.'[@page.page]'`](https://stackoverflow.com/questions/34070987/escaping-a-dot-in-a-map-key-in-yaml-in-spring-boot):

```yaml
content:
  items:
    -
      '''[@page':
        page:
          - /slug
```
- `.[@page.page]`:

```yaml
content:
  items:
    -
      '[@page':
        page:
          - /slug
```

doing it as a single value field, with `header.content.items.@page.page` / `header.content.items[@page.page]`, gives similar results.

is this the intended behavior? is there a way to achieve this, or a workaround?
