### ISSUE TITLE
Form is never processed

### ISSUE THREAD

**Issue by rostwald** [getgrav/grav-plugin-admin#2371]
I've been trying to create an as-simple-as-it-gets form (i.e. copying the example from documentation minus captcha), but the form is never processed.

I also tried removing the whole 'email' block (email settings are working) so the form should only be saved, and even with only the "message:" and "display:" statements in the process-block absolutely nothing happens except the form being reset.
I can basically add or omit whatever I want in the "process:" block, as it doesn't have *any* effect.

markdown for the page:

```
title: Contact
form:
    name: contact
    fields:
        -
            name: name
            label: Name
            placeholder: 'Enter your name'
            autofocus: true
            autocomplete: true
            type: text
            validate:
                required: true
        -
            name: email
            label: Email
            placeholder: 'Enter your email address'
            type: text
            validate:
                rule: email
                required: true
        -
            name: message
            label: Message
            size: long
            placeholder: 'Enter your message'
            type: textarea
            validate:
                required: true
    buttons:
        -
            type: submit
            value: Submit
    process:
        -
            save:
                fileprefix: feedback-
                dateformat: Ymd-His-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %}'
        -
            message: 'Thank you for your feedback!'
        -
            display: thankyou
```

I also tried enabling debug and inline errors in the plugin settings, but no debug information or errors are shown or logged...
