### ISSUE TITLE
Show pages that use the selected page as field type `pages` in frontmatter header

### ISSUE THREAD

**Issue by masetto** [getgrav/grav-plugin-admin#2374]
Hi There,
I created a "pages" field type in the Blueprints:

```yaml
              fields:
                .configuration:
                    type: pages
                    size: medium
                    classes: fancy
                    label: Element
                    start_route: '/configurations'
                    show_all: false
                    show_slug: true
                    show_modular: false
                    show_root: false
```

In frontmatter of the page markdown I have:

```
configurations:
    -
        configuration: /configurations/54006-5-aspo-svolgitore-10-t
```

In admin, when I edit "54006-5-aspo-svolgitore-10-t" page, I'd like to view all pages that have this page in "header.configuration" frontmatter.

Is it possible?

Thanks
