### ISSUE TITLE
Menu Modal Toolbar not showing without admin.super permission

### ISSUE THREAD

**Issue by chraebsli** [getgrav/grav-plugin-admin#2408]
I found an issue regarding the toolbar in the menu modal in pages, which is only showing when the user has `admin.super` permission.

_Currently, I only get this modal without the toolbar with let’s say `user1`:_
![Menu Modal without Toolbar](https://github.com/getgrav/grav-plugin-admin/assets/73113302/2d82bcdf-5ae2-429b-8d22-0775dd83cf4f)

_But with my `admin` user, I get this modal, with the toolbar:_
![Menu Modal with Toolbar](https://github.com/getgrav/grav-plugin-admin/assets/73113302/4f9daa8f-00d6-4051-9512-2d8996ea509f)

I tested this with a fresh Grav + Admin installation without any configuration.

---

## Accounts
Here are my account configs (access only)

### `admin`
```
access:
  site:
    login: true
  admin:
    login: true
    super: true
```

### `user1`
```
access:
  admin:
    login: true
    configuration:
      pages: true
    pages: true
```

**Comment by Fuficek** [comment]
I've recently stumbled upon this issue myself and is really annoying. I hope it'll get fixed soon. Seems simple to fix.

**Comment by rhukster** [comment]
I cannot recreate this currently.  That typically means that it's either a webserver issue, or a plugin-related issue.  Can you please provide me some more information about your setup and all plugins you are using and perhaps we can get to the bottom of this?

**Comment by rhukster** [comment]
BTW, does the "copy" button in the toolbar when editing the page work for you? It functions in much the same way as this popover button does.

**Comment by rhukster** [comment]
Scratch my comments, had the wrong issue up when responding!

**Comment by rhukster** [comment]
What plugins do you have installed?

What account privs do you have?  can you paste a copy of the user's account yaml file? (`user/accounts/username.yaml`).

I think you might have a plugin installed that is causing a conflict as i can't recreate this.

**Comment by Fuficek** [comment]
> > Seems simple to fix.
> 
> You're free to open a PR with the fix;)

I'd like to but I'm not that good at PHP :(

**Comment by pamtbaau** [comment]
@rhukster,

- Download Grav + Admin.
- Surf to site and create a user to login.
Access rights will be:
  ```
  access:
    admin:
      login: true
      super: true
    site:
      login: true
  ```
- Edit current user:
  - Pages: 'Allow'
  - Super user: 'Unset'
  New access rights:
    ```
    access:
      admin:
        login: true
        pages: true
      site:
        login: true
    ```
 - Logoff
 - Sometimes needed to run `$ bin/grav cache`
 - Login
 - Go to pages
 - Click on menu of Typography  => Menu options have disappeared
