### ISSUE TITLE
Check/display new or existing files/medias in page 

### ISSUE THREAD

**Issue by bonnebulle** [getgrav/grav-plugin-admin#2410]
Hello everybody
Am working with the grav-plugin-admin web interface
but some time am using the "folder way" to edit / add contents
and so for images / medias !
For example I can drag-n-drop file directly into  ```pages/test_page/image_1.jpg```

But files I add ( in the folder/manual or admin way )
dont appears into the admin/edit page ! :cry: 

The filepicker show me them, cool
... but, it would be much more easier to show the new added files
directly after/in/under the media field ("media" in blueprint) 

( like when I upload some )
( but for already existing ones )
![image](https://github.com/getgrav/grav-plugin-admin/assets/1598041/b737af5a-7d19-446a-aafe-0cff72e7f569)

My blueprint :
```
            media_files:
              type: file
              label: Médias
              multiple: true
              destination: 'self@'
              random_name: false
              avoid_overwriting: false
              limit: 10
              accept:
                - image/*
```

-----

Some links I follow ( much more about filepicker / pagemediaselect )
- Filepicker form field by flaviocopes · Pull Request #750 · getgrav/grav-plugin-admin
↳ https://github.com/getgrav/grav-plugin-admin/pull/750
- Pagemediaselect should refresh when new media is uploaded · Issue #450 · getgrav/grav-plugin-admin
↳ https://github.com/getgrav/grav-plugin-admin/issues/450
- Dynamic update pagemediaselect fields when pagemedia file is uploaded · Issue #741 · getgrav/grav-plugin-admin
↳ https://github.com/getgrav/grav-plugin-admin/issues/741

-----

So my question is, for now :
How do the admin-plugin is "searching"/"scanning" for new media files ?
What it the task trigger ? Can I force this process to start ?

I follow this question :
```task.addmedia```
https://discourse.getgrav.org/t/issues-with-page-media-in-admin-task-addmedia/1311/6

Maybe using an other cron / routine task ?

Thanks
