### ISSUE TITLE
ISSUE/BUG: Accounts without “SUPER USER” cannot duplicate pages

### ISSUE THREAD

**Issue by Fuficek** [getgrav/grav-plugin-admin#2413]
Hello,
I’ve already submitted this issue to discord, and [Grav Forum](https://discourse.getgrav.org/t/issue-bug-accounts-without-super-user-cannot-duplicate-pages/25406).

**Issue description:**
When I set the role “Super User” to Unset or Denied (because I don’t want my regular page editors to access configs and such. The sub-menu when clicking 3 dots on any page or module in pages disappears (see images), therefore, accounts that are just going to be used to modify and create pages, cannot easily duplicate others. All other permissions have been allowed. Just not SUPER USER. I’m unsure if this is supposed to happen, but is seems like a bug and not a feature to me.
image
![image](https://github.com/getgrav/grav-plugin-admin/assets/91286763/af99ce7c-878a-425d-8864-5fb2a605c6cf)
![image](https://github.com/getgrav/grav-plugin-admin/assets/91286763/05bbad94-a133-4084-a63e-7b8e098fabe4)

**Steps to recreate issue:**
1. Create a new account
2. Give the account all permissions and set only ‘super user’ to Not set/Denied
3. Login into the new account’s admin panel.
4. The option is no longer available.

**Versions:**
- Grav - 1.7.46 (currently newest)
- Admin - 1.10.46 (currently newest) - only modification was a custom theme. The issue persists on the default one as well.

I’d like help as soon as possible please. This issue has been bothering be for a while and I’ve tried to resolve it in discord with my submissions being ignored (Ricardo replied once.) I’m not blaming anyone I’m just desperate for help. Any suggestions???.. Thank you <3

If anything contact me on discord or [Grav Forums](https://discourse.getgrav.org/t/issue-bug-accounts-without-super-user-cannot-duplicate-pages/25406)

**Comment by rhukster** [comment]
I'm not able to recreate this issue.  I have testd with an 'author' user that simply has these permissions:

```
  access:
    admin:
      login: true
      pages:
        list: true
        create: true
        update: true
        read: true
```

They are able to see the copy button in both the listing page and the details page:

![CleanShot 2024-05-27 at 14 17 03@2x](https://github.com/getgrav/grav-plugin-admin/assets/1084697/4cd50a9c-25f7-4ede-b492-bc2aa24b8b7c)

![CleanShot 2024-05-27 at 14 17 22@2x](https://github.com/getgrav/grav-plugin-admin/assets/1084697/8787ceb2-6630-4fb3-b6bf-57f91c35ac48)

![CleanShot 2024-05-27 at 14 17 55@2x](https://github.com/getgrav/grav-plugin-admin/assets/1084697/cfd8680c-617d-4c3e-9780-9b9e6740146b)


What does the actual account `.yaml` file look like? (`user/accounts/username.yaml`)

What plugins do you have installed?

**Comment by Fuficek** [comment]
The account permissions:
```
access:
  site:
    login: true
  admin:
    login: true
    cache: true
    configuration: true
    pages: true
    maintenance: true
    statistics: true
    plugins: true
    themes: true
    tools: true
    users: true
    flex-objects: true
```

My installed plugins:
![image](https://github.com/getgrav/grav-plugin-admin/assets/91286763/bf03d1e9-535c-4adf-a68a-12c581dd5767)
(Webp plugins are disabled)

I've tried a fresh installation and the issue persists.
