### ISSUE TITLE
Enable 'Folder Numeric Prefix' by default.

### ISSUE THREAD

**Issue by felixdenoix** [getgrav/grav-plugin-admin#2441]
Hello,

Thank you for the grav CMS and all the tools that have been build around.

The problem I'm facing is that I do not find a way to enable by default the ordering behavior of the modules in modular pages. I haven't found options to do so in the main configuration and I've tried to create a blueprint for my component overloading the option without success.

Here is the blueprint I created for my module:
```yaml
title: Heading
'@extends': default

form:
  fields:
    tabs:
      fields:
        advanced:
          fields:
            columns:
              fields:
                column1:
                  fields:
                    name:
                      label: test
                      default: modular/heading
                      '@data-options': '\Grav\Common\Page\Pages::modularTypes'
                column2:
                  fields:
                    ordering:
                      default: 1
            overrides:
              fields:
                header.template:
                  default: modular/heading
                  '@data-options': '\Grav\Common\Page\Pages::modularTypes'
```
Its located in: `user/themes/custom-theme/blueprints/pages/modular/heading.yaml`

**Comment by felixdenoix** [comment]
I managed to have something working using a custom form that extended the admin one that I located here
`user/themes/CUSTOM_THEME/blueprints/admin/pages/modular_new.yaml` . The interesting point here is to force the ordering of the newly created element using the value `@self.siblings` for the `order` field 

```yaml
# original blueprint here: user/plugins/admin/blueprints/admin/pages/modular_new.yaml
title: New module
'@extends':
  type: modular_new
  context: blueprints://admin/pages

form:
  fields:
    order:
      type: hidden
      default: "@self.siblings"

```
