### ISSUE TITLE
Pages Field Not Displaying All Pages in Admin Panel

### ISSUE THREAD

**Issue by ChristianaHoJo** [getgrav/grav-plugin-admin#2444]
We are experiencing an issue in the Grav Admin Plugin where the pages field does not display all pages in the dropdown list. Our Grav site contains over 1000 pages, and despite using the following blueprint configuration:

```
.link:
  type: pages
  size: large
  classes: fancy
  show_all: true
  show_root: true
  show_modular: true
  toggleable: true
  label: Internal Link (Page or Section)
```

The dropdown stops scrolling at a certain point, even though additional pages exist in the system. The missing pages are confirmed via `var_dump($list);` in `system/src/Grav/Common/Page/Pages.php`, function `getList()`, but they do not appear in the dropdown HTML.

Steps to Reproduce:

- Run a Grav site with over 1000 pages.
- Use the pages field in a blueprint with `show_all: true.`
- Open the Admin Panel and try to select a page.
- Notice that the dropdown does not display all available pages.

Observed Behavior:

- The dropdown stops displaying pages at a certain threshold.
- Missing pages are present in the backend (var_dump confirms they exist).
- The issue may be caused by a JavaScript limitation rather than the backend query.

I also opened an Issue in[ Grav Forum](https://discourse.getgrav.org/t/pages-field-not-showing-all-pages-in-admin-panel-limit/27764/3).
