### ISSUE TITLE
System configuration in Admin Panel

### ISSUE THREAD

**Issue by maxlysenko** [getgrav/grav-plugin-admin#27]
* If there is no `system.yaml` file in `user/config` folder admin panel saves changes into `system/config/system.yaml` instead of creating new `user/config/system.yaml` file. Maybe it's better to create new user configuration than overwrite initial system configuration?

* When saving configuration, two keys (`markdown` and `page`) with value `1` are added into `system.yaml` file:
``` yaml
markdown: '1'
page: '1'
```
Next, each time you save configuration, values of `1` are added to these keys, so it becomes something like:
``` yaml
markdown:
  - '1'
  - '1'
  - '1'
  - '1'
  - '1'
page:
  - '1'
  - '1'
  - '1'
  - '1'
  - '1'
```
What is this intended for?

* It would be useful to see which configuration file (`system/config/system.yaml` or `user/config/system.yaml` or `user/localhost/config/system.yaml` or other environment configuration) is in use and will be saved, or even add an option to select configuration file for editing.
