### ISSUE TITLE
Lists withs selects

### ISSUE THREAD

**Issue by lennerd** [getgrav/grav-plugin-admin#273]
I'm trying to have a select field inside a list item form via blueprint configuration:

``` yaml
form:
  fields:
    tabs:
      fields:
        # Images
        images:
          type: tab
          title: Images
          fields:
            header.images:
              name: images
              type: list
              label: Images
              fields:
                .name:
                  type: select
                  size: medium
                  classes: fancy
                  '@data-options': '\Grav\Theme\iapk::images'
                  label: Image
                .alt:
                  type: text
                  label: Description
```

I already found out that the `@data-options` option from the `.name` field is not parsed from the `Grav\Common\Data\Blueprint` class, but I'm not able to fix this to creat a PR for this. Any ideas?

I already testes the `\Grav\Theme\iapk::images` function inside a normal select form field, which worked just fine.

<img width="1045" alt="screenshot 2015-11-14 15 42 39" src="https://cloud.githubusercontent.com/assets/1609692/11164066/5e21686a-8ae6-11e5-8415-c2299cef2e1a.png">

**Comment by lennerd** [comment]
Yes, it's a theme for a client. I think it's much easier for you to spot the problem if I create simplified copy of my Grav installation. Will send you a copy by thursday.

**Comment by rhukster** [comment]
Did you manage to get this zip together?

**Comment by lennerd** [comment]
Sorry. Didn't had the time yet. Will make a zip file till Tuesday, I promise.

**Comment by rhukster** [comment]
K, thanks.

**Comment by lennerd** [comment]
Hey there.

I managed to build a simple demo including the issue I had with select fields and `@data-options` properties inside list fields.

https://www.dropbox.com/s/20v81uw9vi6kbk0/grav-list-select-demo.zip?dl=0

Go to `/admin/pages/demo/_buttons-demo` and you see two different selects. On inside the outer tab called Buttons and one inside a list of buttons. While the select inside the tab correctly shows every route of the page, the select inside the list item only contains the default option I provided.

![screenshot 2015-11-24 10 01 39](https://cloud.githubusercontent.com/assets/1609692/11362204/7ffba4ba-9292-11e5-9d72-d00b4a6676f5.png)

From the corresponding blueprint file `/user/themes/antimatter-bug/blueprints/modular/buttons-bug.yaml`:
``` yaml
title: Buttons Bug
'@extends': default

form:
  fields:
    tabs:
      fields:
        advanced:
          fields:
            columns:
              fields:
                column1:
                  fields:
                    name:
                      default: modular/buttons-bug
                      '@data-options': '\Grav\Common\Page\Pages::modularTypes'
            overrides:
              fields:
                header.template:
                  default: modular/buttons-bug
                  '@data-options': '\Grav\Common\Page\Pages::modularTypes'
        buttons:
          type: tab
          title: Buttons
          fields:
            header.buttons:
              name: buttons
              type: list
              label: Buttons

              fields:
                .title:
                  type: text
                  label: Title
                .route:
                  label: Route inside a List
                  type: select
                  classes: fancy
                  '@data-options': '\Grav\Common\Page\Pages::parents'
                  '@data-default': '\Grav\Plugin\admin::route'
                  options:
                    '/': PLUGIN_ADMIN.DEFAULT_OPTION_ROOT
            header.demo_route:
              label: Route inside a Tab
              type: select
              classes: fancy
              '@data-options': '\Grav\Common\Page\Pages::parents'
              '@data-default': '\Grav\Plugin\admin::route'
              options:
                '/': PLUGIN_ADMIN.DEFAULT_OPTION_ROOT
```
