### ISSUE TITLE
Date field does not display datepicker in admin

### ISSUE THREAD

**Issue by jwachuta** [getgrav/grav-plugin-admin#281]
The documentation at http://learn.getgrav.org/advanced/blueprints lists support for both a "date" and a "datetime" field in custom admin blueprints. Creating a form with the "date" field, however, fails to display the date selector widget in admin, and the input field also appears unstyled, with browser default borders, etc. 

To reproduce (in default antimatter theme), copy the following blueprint to /user/themes/antimatter/blueprints/date.yml, then use Grav Admin to add a page using the "Date" page file & click on the "Date" tab to see the form.

```
title: Date
@extends:
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:

      fields:
        date:
          type: tab
          title: Date

          fields:

            header.date:
              type: date        # lacks datepicker & styling
              label: date
            header.datetime:
              type: datetime    # works as expected
              label: datetime 
```
