### ISSUE TITLE
"Multiple" Markdown editors on same page

### ISSUE THREAD

**Issue by grangeway** [getgrav/grav-plugin-admin#285]
Consider a page based on a blueprint, where the blueprint contains multiple markdown editors:

For example, a blueprint.yaml extract similar to the below rendering a custom tab:
```
            header.text1:
              type: markdown
              validate:
                type: textarea

            header.text2:
              type: markdown
              validate:
                type: textarea
```

This renders a custom tab with 2 markdown editors on the same tab.

Clicking the "B" bold icon on the first markdown editor, changes focus to the last markdown editor on the page and inserts ** **, instead of the expected behaviour of inserting at the current active cursor  location

version 1.0.0-rc.4
