### ISSUE TITLE
List type in YAML Blueprints saves with an extra empty set when using Normal mode

### ISSUE THREAD

**Issue by benblee** [getgrav/grav-plugin-admin#323]
*Version: Admin Panel  v1.0.0-rc.7*

In the Admin area editing a modular page, if there is a list item in the blueprints, it’s adding an empty value on saving. So the following is what you could enter just in the .md file and it works fine:

```
title: Gallery
styles: center-title
gallery:
    -
        image: arches.jpg
        title: 'Arches National Park'
        description: 'Summer 2015'
    -
        image: arches.jpg
        title: 'Arches National Park'
        description: 'Summer 2015’
```

But if you use the admin area and **Normal** mode, it will save it with an extra empty set:

```
title: Gallery
styles: center-title
gallery:
    0:
        image: arches.jpg
        title: 'Arches National Park'
        description: 'Summer 2015'
    1:
        image: arches.jpg
        title: 'Arches National Park'
        description: 'Summer 2015'
    '*':
        image: ''
        title: ''
        description: ‘’
```

Editing and Saving in **Expert** mode works fine and as expected. This issue only shows in **Normal** mode.

This is the YAML for this example's blueprint:

```
title: Gallery
@extends: default

form:
  fields:
    tabs:
      fields:
        advanced:
          fields:
            columns:
              fields:
                column1:
                  fields:
                    name:
                      default: modular/gallery
                      @data-options: '\Grav\Common\Page\Pages::modularTypes'
            overrides:
              fields:
                header.template:
                  default: modular/gallery
                  @data-options: '\Grav\Common\Page\Pages::modularTypes'
        styles:
          type: tab
          title: Row Style
          fields:
            header.styles:
              type: textarea
              label: CSS Classes

        gallery:
          type: tab
          title: Images
          fields:
            header.gallery:
              name: images
              type: list
              label: Images

              fields:
                .image:
                  type: text
                  label: Image
                .title:
                  type: text
                  label: Title
                .description:
                  type: text
                  label: Description
```
