### ISSUE TITLE
Undefined index: lang error when saving in a new language

### ISSUE THREAD

**Issue by adelnoureddine** [getgrav/grav-plugin-admin#365]
Hello,

I am having a problem when trying to save a page into a new language.
An "Undefined index: lang" appears (see screenshot below: http://s30.postimg.org/l42cg3yin/error1.png).

Using: Grav 1.0.5, Grav Admin 1.0.3, PHP Version 5.4.39-0+deb7u2

system.yaml:
```
languages:
  supported:
    - en
    - fr
    - de
    - nl
  include_default_lang: false
  translations: true
  translations_fallback: true
  session_store_active: false
  http_accept_language: false
  override_locale: false
```
