### ISSUE TITLE
Untranslated message on logout screen

### ISSUE THREAD

**Issue by martinsik** [getgrav/grav-plugin-admin#378]
When you logout you can see for a few seconds [`logout.html.twig`](https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/templates/logout.html.twig) with untranslated message `PLUGIN_ADMIN.LOGGED_OUT` which is probably because it uses `t` Twig filter instead of `tu`.

I guess it's because `logout.html.twig` is actually outside admin, but `login.html.twig` uses `tu` as well. 

This also got me thinking that there's actually no way you can see `login.html.twig`, `logout.html.twig` and similar pages translated because you set language to a specific admin user which is valid only after you log in.

**Comment by rhukster** [comment]
What is your default language?

**Comment by martinsik** [comment]
I'm using default english but I don't think it matters.

**Comment by flaviocopes** [comment]
Can you paste your system.yaml `languages` settings?

**Comment by martinsik** [comment]
```yaml
languages:
  include_default_lang: false
  translations: false
  translations_fallback: true
  session_store_active: false
  http_accept_language: false
  override_locale: false
```
