### ISSUE TITLE
Blueprints: List inside a list

### ISSUE THREAD

**Issue by khanduras** [getgrav/grav-plugin-admin#383]
team.md file snippet:
```yaml
people:
    - name: Kay Garland
      pic: 1.jpg
      position: Lead Designer
      social:
        - title: twitter
          url: '#'
        - title: facebook
          url: '#'
        - title: stack-overflow
          url: '#'
```
team.yaml blueprint snippet:
```yaml
fields:
  header.people:
    name: people
    type: list
    label: People
    fields:
      .name:
        type: text
        label: Name
      .pic:
        type: text
        label: Image
      .position:
        type: text
        label: Position
      .social:
        name: social
        type: list
        label: Social Networks
        fields:
          .title:
            type: text
            label: Title
          .url:
            type: text
            label: URL
```
It ends up breaking the Admin Page editor but is fine when I remove the .social leg of the file. It adds two social networks when you click Add Item and won't even add a new person at the bottom of that list.

Is this the correct syntax for a list within a list?
