### ISSUE TITLE
Question: Avoid writing unneccessary headers to file

### ISSUE THREAD

**Issue by Sommerregen** [getgrav/grav-plugin-admin#389]
Hi @rhukster and @flaviocopes,

I have a question regarding my latest additions in my **External Links** plugin. My plugin injects a blueprint for header variables in the admin editior (see https://github.com/Sommerregen/grav-plugin-external-links/blob/master/blueprints/external_links.yaml ). All header variables are toggleable meaning one can enable or disable them. But here comes the problem: even when those are disabled the full set of data are written to the files

```yaml
external_links
  process: true
  title: false
  no_follow: true
  mode: active
  target: _blank
```

Is there a way to prevent this? Paul is concerned it may confuse other instructors using his course companion skeleton and I don't know how to change the blueprint to make it happen...
