### ISSUE TITLE
Issue with toggleable inside a list

### ISSUE THREAD

**Issue by flaviocopes** [getgrav/grav-plugin-admin#451]
Branch: `develop`.

Example code:

```yaml
countries:
  type: list
  label: Countries settings
  help: Set countries where people can buy from, and corresponding taxes. Set specific countries as disabled.

  fields:

    .name:
      label: Country
      type: select
      classes: fancy
      '@data-options': '\Grav\Plugin\ShoppingcartPlugin::shippingCountries'
      validate:
        type: commalist

    .allow:
      label: Allow
      type: toggle
      highlight: 1
      default: 1
      options:
        1: PLUGIN_ADMIN.ENABLED
        0: PLUGIN_ADMIN.DISABLED
      validate:
        type: bool

    .tax_percentage:
      toggleable: true
      label: Tax percentage
      type: text
      help: The tax percentage for this country
      validate:
          type: int
```

Notice the last field of the list has `toggleable: true`
Visualization of the problem: 

![qe8rw3eurk](https://cloud.githubusercontent.com/assets/11783388/13728920/dd585e46-e927-11e5-9fdb-737dae9df004.gif)

When toggling visibility of an element, the whole list is being disabled instead of just the single field inside the list item.

This is probably not something expected to work yet, issuing to keep track.
