### ISSUE TITLE
Issue when saving tab-based plugin configuration

### ISSUE THREAD

**Issue by flaviocopes** [getgrav/grav-plugin-admin#452]
E.g. Login Plugin, latest develop (not latest published release, latest `develop` branch), has the plugin configuration separated in 2 tabs.

When saving it, I get

```yaml
tab-login_registration: login
```

appended to the saved plugin config yaml.

If I have multiple tabs, I get for example

```yaml
tab-general_user_interface_countries_cart_shipping_advanced: general
```

when tabs are named, otherwise 

```yaml
tab-0_1_2_3_4_5: '0'
```

if tabs are unnamed (using `-`)

**Comment by flaviocopes** [comment]
Not happening on Pages, where there are tabs too, but don't notice any special syntax to avoid this behavior.

**Comment by w00fz** [comment]
They shouldn't be saved, they are tabs, but that's the correct syntax and how they get stored in cookie. The long name is to work around the limitation of not knowing any Id for the tabs container as it was discussed on slack a couple days ago, so it collects all the tabs title names.

Checkout adminp that also has tabs for Configuration, and as you said also page has tabs. They really shouldn't get saved when changed.

**Comment by flaviocopes** [comment]
Ah now I see. I need to add `ignore: true` to the tabs field:

```yaml
form:
  validation: loose
  fields:

    tabs:
      type: tabs
      class: subtle
      ignore: true

      fields:
        login:
          type: tab
          title: PLUGIN_LOGIN.BTN_LOGIN
```

it works in Admin Pro, but not in Login. Need to find out why.
