### ISSUE TITLE
Themes > forms > file type

### ISSUE THREAD

**Issue by rikemsen** [getgrav/grav-plugin-admin#478]
Hi there,

I think it would be interesting to have a small thumbnail instead of the whole picture file when using "file" type in theme configuration page.

I have : 
```
form:
  validation: loose
  fields:
    custom_slide_1:
      type: file
      label: Image slide 1
      destination: 'user/themes/receptar/images/slideshow'
      blueprint: 'themes.receptar'
      accept:
        - image/*
```
And when I upload a picture, It is displayed in full width... A bit large for 1920x1080 images...

Best regards,
rikemSen
