### ISSUE TITLE
Blueprint: The Pages field bug when selecting multiple: true

### ISSUE THREAD

**Issue by adanarchila** [getgrav/grav-plugin-admin#484]
Hi, I was trying to list the pages in a custom blueprint page by doing: 

```
header.list_pages:
    type: pages
    size: medium
    classes: fancy
    label: PLUGIN_ADMIN.HOME_PAGE
    show_all: false
    show_modular: false
    show_root: false
    multiple: true
```

I was playing around with the different types of validations and I was able to save the pages I selected (I checked this in the expert mode).

But they didn't appear in the frontend, it only worked when I set the multiple: false

**Comment by adanarchila** [comment]
Btw, I found a workaround and it was to use the custom field type: list and inside each item list I included a type: pages with multiple set to false.

**Comment by flaviocopes** [comment]
Yes. This is a shortcoming of the current Admin. Version `1.1`, with a public beta soon, will fix this.

It will need an additional validate parameter to save the values as a comma separated list:

```
            header.list_pages:
              type: pages
              size: medium
              classes: fancy
              label: PLUGIN_ADMIN.HOME_PAGE
              show_all: false
              show_modular: false
              show_root: false
              multiple: true
              validate:
                type: commalist
```
