### ISSUE TITLE
Override Taxonomy Fields in Blueprints

### ISSUE THREAD

**Issue by Algorithm518** [getgrav/grav-plugin-admin#501]
I have a blueprint I am working on that utilizes the Taxonomy type and am looking to override one of the fields so I can display it in a different manner than the default 'select'-ize type.

The blueprint resembles similar to below:
```
header.taxonomy:
  type: taxonomy
  label: Taxonomy
  multiple: true
  validate:
    type: array

header.taxonomy.category:
    type: toggle
    label: Category
    highlight: 1
    options:
        1: YES
        0: NO
    validate:
        type: bool
```

This usually results in an error however. I have tried tweaking the source to skip the creation of the overridden items, but then I face an issue where the items in the .yaml file are being created as a comma separated string and not a list like it should.

**Comment by rhukster** [comment]
@mahagr could you answer this one?

**Comment by mahagr** [comment]
I think this is fully possible only in Grav 1.1 where you can remove and reset existing fields (`replace@: true`). Right now you may have an issue where old properties still exist and mess up with the form.

Though, that said, there is larger issue in your blueprints: I don't think that blueprint recognises the format you're using. Also only `type: array` supports nested sets; try this instead:

```
header.taxonomy:
  replace@: true
  type: array
  label: Taxonomy
  multiple: true
  validate:
    type: array

  fields:
    .category:
      type: toggle
      label: Category
      highlight: 1
      options:
          1: YES
          0: NO
      validate:
          type: bool
```

Unfortunately by doing this, you will loose all existing taxonomy categories from your list. In order to fix that you would need to somehow use `data-value@:` property to fetch all the options -- this in turn would prevent you from saving the data.

So in the end I'm not sure if it is possible to do this without creating your own form field to deal with it.
