### ISSUE TITLE
Creating a list that is full width (AKA "List Inception" or foreach)

### ISSUE THREAD

**Issue by Vivalldi** [getgrav/grav-plugin-admin#503]
Currently it is not possible to remove the label field from lists and make the lists full width.
Looking like this
![](http://i.imgur.com/fJZb5YV.png)

I would prefer for something like this.
![](http://i.imgur.com/gPBZG7O.png)

The list type works well with small button additions but when you want to have a list of something large that in turn has a list underneath it makes it difficult not only on the eye but also keeping track of "groups".

**Comment by rhukster** [comment]
Try adding this to the field:

```
style: vertical
```

This is how the title/content fields in the `default.yaml` page are able to go full width (label if any goes above)

**Comment by Vivalldi** [comment]
I have added `style: vertical` and it does not apply the styling.

Current blueprint for reference
```
title: Equipment List
'@extends': default

form:
  fields:
    tabs:
      fields:
        equipment:
          type: tab
          title: Equipment
          fields:
            header.compartments:
              name: compartments
              label: Compartments
              type: list
              style: vertical
              btnLabel: Add Compartment
              fields:
                .name:
                  type: text
                  label: Compartment Name
                .items:
                  type: list
                  label: Equipment Items
                  btnLabel: Add Equipment Item
                  fields:
                    .name:
                      type: text
```
