### ISSUE TITLE
Permissions for changing and deleting pages

### ISSUE THREAD

**Issue by fvsch** [getgrav/grav-plugin-admin#512]
It would be excellent if we could lock down some pages so that users can only edit specific pages, not the whole site. Maybe something on top of user groups?

For instance there could be default permissions, perhaps in `user/config/admin/admin.yaml` (or maybe it would make more sense in blueprints, which allows setting this config depending on template):

``` yaml
# Only admins can delete pages
permissions:
  pages:
    write: [admin, editor]
    delete: [admin]
```

And YAML config in each page could overwrite these default settings:

``` yaml

---
title: Awesome page
permissions:
  write: [admin] # Limit changes to the admin group in the admin plugin
  delete: [] # Protect this page from deletion from the admin plugin

---
```
## Use cases for locking down a page
- If your site structure rests on a few "container" pages (blog, section1, section2…) and you want to avoid careless deletions of _all the content_ in a section by locking the level 1 pages.
- If you want to protect the error page or other "technical" pages.
- A business communication website where one editor or group of editors should be able to create new blog posts, perhaps modify the root "blog" page but NOT delete it, and should not be able to modify (let alone delete) other pages in other sections (or the home page).
## Permission types

I think a simple implementation could be limited to 2 permissions:
- write
- delete

Excluding these other common permission types (less useful or harder to manage):
- read (the need to hide content to admin users seems low)
- page ownership (write/delete your "own" pages) -> adds a big level of complexity
- addchild (controlling whether a user group can add a child page inside a page) -> adds some complexity too
