### ISSUE TITLE
Can't restrict access on config "System" tab.

### ISSUE THREAD

**Issue by RomainFallet** [getgrav/grav-plugin-admin#553]
I added an access property in my `user/plugins/admin/pages/admin/system.md` in order to restrict the access of my config System tab to a specific user :
```
access:
    admin.azertyuiop: true
```

In my user yaml file, if have this :
```
access:
  admin:
    login: 'true'
    maintenance: 'true'
    pages: 'true'
    configuration: 'true'
    azertyuiop: 'false'
```
But I t didn't restrict the access to this page.
