### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by laszlokorte** [getgrav/grav-plugin-admin#625]
I just downloaded Grav+AdminPlugin 1.1 Beta.

I created a new user with the following permissions:

```
access:
  admin:
    login: 'true'
    pages: 'true'
  site:
    login: 'true'
```

If I login with this user I get an red error box in the upper right corner:

```
Unexpected token < in JSON at position 0 at SyntaxError: Unexpected token < in JSON at position 0s @ admin.min.js?d3e35b819e:3
```

If I add `super: true` to the permissions the error disappears.
