### ISSUE TITLE
Unexpected error messages on Save

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#626]
I've started to use the updated Frontmatter editor in b5, and I am seeing some unexpected error messages when I try to Save.

For example:
![2016-05-28_06-44-11](https://cloud.githubusercontent.com/assets/1812771/15627900/ce4d7452-24a7-11e6-9c4c-38e65b564251.png)

When trying to save this page:
```
---
title: Home
blog_url: blog
body_classes: header-image fullwidth

sitemap:
    changefreq: monthly
    priority: 1.03

modular_content:
    items: '@self.modular'
    order:
        dir: desc

content:
    items: '@self.children'
    order:
        by: date
        dir: desc
    limit: 14
    pagination: true

feed:
    description: Course Hub Description
    limit: 10

pagination: true
---

```

Earlier I seemed to get a bit different message with the same Frontmatter (this is the image I shared in the Gitter room):
![2016-05-26_06-18-34](https://cloud.githubusercontent.com/assets/1812771/15627929/68f51410-24a8-11e6-8d55-98eaf1ac311d.png)

I've also attached the full user folder (which I am testing with b5).

Thanks very much,
Paul
[user.zip](https://github.com/getgrav/grav-plugin-admin/files/287759/user.zip)
