### ISSUE TITLE
Taxonomy-Field in Theme misbehaves

### ISSUE THREAD

**Issue by MaZderMind** [getgrav/grav-plugin-admin#652]
Im setting up a Theme-Configuration where the Editor can configure Colors for a Taxonomy-Category.

My theme-blueprint.yaml looks like this:
```
form:
  validation: loose
  fields:
    categories:
      type: list
      label: Category-Colors- and Images
      fields:
        .taxonomy:
          type: taxonomy
          label: "Lala"
          multiple: true
          validate:
            type: array
        .color:
          type: text
          placeholder: "#FFFFFF"
          label: Color
          validate:
            pattern: "\#[0-9A-Fa-f]{6}"
```

The Form misbehaves in multiples ways:
![bildschirmfoto vom 2016-06-05 20-40-59](https://cloud.githubusercontent.com/assets/142237/15807404/fe219098-2b5d-11e6-810d-a42f19943beb.png)

 - [ ] The Label is always "Category", independent on what is configured with the `label`-Option
 - [ ] When adding a new Item (see 3rd row in the Screenshot) the Taxonomy-Box presents a Multiple-Selector independent of the actual value of the `caregory`-Option
 - [ ] When saved, the Editor changes to another Multiple-Selector which is now empty, even the previous editor-Box saved some Data:
```
categories:
  -
    color: '#00FF00'
    taxonomy:
      category:
        - Houses
```
 - [ ] When entering some Categories into the second kind of Editor, they are saved as a String:
```
categories:
  -
    color: '#00FF00'
    taxonomy:
      category:
        - 'Tech,Houses'
```

**Comment by rhukster** [comment]
Probably the same thing as with File from #653.  Lists are very different beasts because they are dynamic.  Certain fields are just not flexible to work with dynamic lists.  Taxonomy fields are in the same boat as their logic is already dynamic and quite specific to the way a page stores taxonomy. 

If you want to use a tag-style list, you can do it with a regular `select` field using `commalist`, but you cannot use `taxonomy` field:
```
header.tag_list:
  type: selectize
  size: large
  label: Tag List
  classes: fancy
  validate:
    type: commalist
```
