### ISSUE TITLE
File-Field in Theme misbehaves

### ISSUE THREAD

**Issue by MaZderMind** [getgrav/grav-plugin-admin#653]
Similar to the Taxonomy-Field (#652) a File-Field in my Theme's blueprint misbehaves.

The blueprint.yaml looks like this:
```
form:
  validation: loose
  fields:
    categories:
      type: list
      label: Category-Colors- and Images
      fields:
        .taxonomy:
          type: taxonomy
          label: Lala
          multiple: false
          validate:
            type: array
        .color:
          type: text
          placeholder: "#FFFFFF"
          label: Color
          validate:
            pattern: "\#[0-9A-Fa-f]{6}"
        .custom_file:
          type: file
          label: A Label
          destination: 'user/themes/my-theme/assets'
          blueprint: 'themes.mytheme'
          accept:
            - image/*
```

When selecting a File to upload, the following data is saved into `user/config/themes/themename.yaml`:
```
categories:
  1:
    taxonomy:
      category:
        - Tech
    color: '#00FF00'
    custom_file:
      - free-projects.jpg
```

The file seems to not be stored anyway (at least under that name) and the admin-theme fails to render with this error message and a rather unuseful stacktrace:
```
Twig_Error_Runtime
An exception has been thrown during the rendering of a template ("Array to string conversion") in "forms/fields/file/file.html.twig" at line 12.
```

The error points to the following line in `user/plugins/admin/themes/grav/templates/forms/fields/file/file.html.twig`:
```
<img src="{{ uri.rootUrl == '/' ? '/' : uri.rootUrl ~ '/'}}{{ value }}" alt="{{ value|replace({(files.destination ~ '/'): ''}) }}" />
```
and seems to refer to `value` now being an array.
