### ISSUE TITLE
File type blueprint in Theme configuration page doesn't seem to work properly

### ISSUE THREAD

**Issue by rlynjb** [getgrav/grav-plugin-admin#680]
Hi all,
I am trying to setup a field for file upload on my theme configuration.

is there a sample for File type in Theme configuration?
The following i what I got on my blueprints.yaml file

```yaml
form:
  validation: loose
  fields:

    General:
      type: section
      title: General
      underline: true
      fields:
 
        general_logo:
          type: file
          label: Logo
          destination: '/user/themes/startuply/img/'
          blueprint: 'themes.startuply'
          accept: [ 'image/png' ]
          multiple: false
        general_about:
          type: text
          label: About
```

the file doesn't upload and the destination path doesn't seem to take into account. I would get a file path like '/image.png' on the root directory of grav core
