### ISSUE TITLE
Nested lists + pagemediaselect in blueprint cause error

### ISSUE THREAD

**Issue by fredrikekelund** [getgrav/grav-plugin-admin#683]
I'm getting an error screen about the maximum nesting level being reached when using three nested lists in a blueprint together with a pagemediaselect control. Here's the error output, as well as the blueprint that seems to be causing error.

If I remove the last list control - ie. `.images`, which is a pagemediaselect - the error doesn't appear. Nor does it appear if I move the `.images` control one list up in the hierarchy. 

```
¨Whoops\Exception\ErrorException thrown with message "Maximum function nesting level of '100' reached, aborting!"

Stacktrace:
#99 Whoops\Exception\ErrorException in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Node.php:145
#98 Twig_Node:getAttribute in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Node/Expression/Name.php:27
#97 Twig_Node_Expression_Name:compile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Compiler.php:97
#96 Twig_Compiler:subcompile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Node/Expression/GetAttr.php:31
#95 Twig_Node_Expression_GetAttr:compile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Compiler.php:97
#94 Twig_Compiler:subcompile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Node/Expression/Binary.php:29
#93 Twig_Node_Expression_Binary:compile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Compiler.php:97
#92 Twig_Compiler:subcompile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Node/Expression/Call.php:70
#91 Twig_Node_Expression_Call:compileArguments in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Node/Expression/Call.php:30
#90 Twig_Node_Expression_Call:compileCallable in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Node/Expression/Filter.php:37
#89 Twig_Node_Expression_Filter:compile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Compiler.php:97
#88 Twig_Compiler:subcompile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Node/Expression/Binary.php:23
#87 Twig_Node_Expression_Binary:compile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Compiler.php:97
#86 Twig_Compiler:subcompile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Node/Expression/Call.php:70
#85 Twig_Node_Expression_Call:compileArguments in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Node/Expression/Call.php:30
#84 Twig_Node_Expression_Call:compileCallable in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Node/Expression/Filter.php:37
#83 Twig_Node_Expression_Filter:compile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Compiler.php:97
#82 Twig_Compiler:subcompile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Node/Print.php:30
#81 Twig_Node_Print:compile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Node.php:110
#80 Twig_Node:compile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Compiler.php:97
#79 Twig_Compiler:subcompile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Node/If.php:53
#78 Twig_Node_If:compile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Node.php:110
#77 Twig_Node:compile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Compiler.php:97
#76 Twig_Compiler:subcompile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Node/Block.php:34
#75 Twig_Node_Block:compile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Node.php:110
#74 Twig_Node:compile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Node.php:110
#73 Twig_Node:compile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Compiler.php:97
#72 Twig_Compiler:subcompile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Node/Module.php:82
#71 Twig_Node_Module:compileTemplate in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Node/Module.php:52
#70 Twig_Node_Module:compile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Compiler.php:86
#69 Twig_Compiler:compile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:655
#68 Twig_Environment:compile in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:671
#67 Twig_Environment:compileSource in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:396
#66 Twig_Environment:loadTemplate in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:503
#65 Twig_Environment:resolveTemplate in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:279
#64 Twig_Template:loadTemplate in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:403
#63 __TwigTemplate_1a42031a002f2522d993cf70afd35e19a7418ddce5711cb358a27a9d24bdbd32:block_contents in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:167
#62 Twig_Template:displayBlock in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:403
#61 __TwigTemplate_26be69c75519896a83b8d8bee3954e6110f40ecd494b7117e23bc24ba4db1203:block_field in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:167
#60 Twig_Template:displayBlock in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:403
#59 __TwigTemplate_26be69c75519896a83b8d8bee3954e6110f40ecd494b7117e23bc24ba4db1203:doDisplay in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:387
#58 Twig_Template:displayWithErrorHandling in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:355
#57 Twig_Template:display in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:403
#56 __TwigTemplate_1a42031a002f2522d993cf70afd35e19a7418ddce5711cb358a27a9d24bdbd32:doDisplay in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:387
#55 Twig_Template:displayWithErrorHandling in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:355
#54 Twig_Template:display in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:403
#53 __TwigTemplate_1a42031a002f2522d993cf70afd35e19a7418ddce5711cb358a27a9d24bdbd32:block_contents in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:167
#52 Twig_Template:displayBlock in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:403
#51 __TwigTemplate_26be69c75519896a83b8d8bee3954e6110f40ecd494b7117e23bc24ba4db1203:block_field in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:167
#50 Twig_Template:displayBlock in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:403
#49 __TwigTemplate_26be69c75519896a83b8d8bee3954e6110f40ecd494b7117e23bc24ba4db1203:doDisplay in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:387
#48 Twig_Template:displayWithErrorHandling in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:355
#47 Twig_Template:display in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:403
#46 __TwigTemplate_1a42031a002f2522d993cf70afd35e19a7418ddce5711cb358a27a9d24bdbd32:doDisplay in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:387
#45 Twig_Template:displayWithErrorHandling in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:355
#44 Twig_Template:display in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:403
#43 __TwigTemplate_1a42031a002f2522d993cf70afd35e19a7418ddce5711cb358a27a9d24bdbd32:block_contents in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:167
#42 Twig_Template:displayBlock in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:403
#41 __TwigTemplate_26be69c75519896a83b8d8bee3954e6110f40ecd494b7117e23bc24ba4db1203:block_field in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:167
#40 Twig_Template:displayBlock in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:403
#39 __TwigTemplate_26be69c75519896a83b8d8bee3954e6110f40ecd494b7117e23bc24ba4db1203:doDisplay in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:387
#38 Twig_Template:displayWithErrorHandling in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:355
#37 Twig_Template:display in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:403
#36 __TwigTemplate_1a42031a002f2522d993cf70afd35e19a7418ddce5711cb358a27a9d24bdbd32:doDisplay in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:387
#35 Twig_Template:displayWithErrorHandling in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:355
#34 Twig_Template:display in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:403
#33 __TwigTemplate_8e496b8e80dc2ddd4f197e734e3a197e19150d68b6b45aaf4ae74b17c1b225a2:doDisplay in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:387
#32 Twig_Template:displayWithErrorHandling in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:355
#31 Twig_Template:display in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:403
#30 __TwigTemplate_46ab43b9423915a8926d085be52cd5b0cdc9278d9059353afaeacde98e65a089:doDisplay in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:387
#29 Twig_Template:displayWithErrorHandling in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:355
#28 Twig_Template:display in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:403
#27 __TwigTemplate_5d939cfc138904646190192b8bede5123df8fa8cbe9852b81aaf35bec94d76c4:doDisplay in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:387
#26 Twig_Template:displayWithErrorHandling in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:355
#25 Twig_Template:display in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:403
#24 __TwigTemplate_82264893f892c5563c3dec4bc71c71dacfe2c893461d08695086d59721b5eb87:block_content in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:167
#23 Twig_Template:displayBlock in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:403
#22 __TwigTemplate_fba2699a61263291b8e9030b271f20c95313bfcdaef0663c89b87f8eaf45d89f:block_page in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:167
#21 Twig_Template:displayBlock in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:403
#20 __TwigTemplate_fba2699a61263291b8e9030b271f20c95313bfcdaef0663c89b87f8eaf45d89f:block_body in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:167
#19 Twig_Template:displayBlock in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:403
#18 __TwigTemplate_fba2699a61263291b8e9030b271f20c95313bfcdaef0663c89b87f8eaf45d89f:doDisplay in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:387
#17 Twig_Template:displayWithErrorHandling in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:355
#16 Twig_Template:display in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:403
#15 __TwigTemplate_82264893f892c5563c3dec4bc71c71dacfe2c893461d08695086d59721b5eb87:doDisplay in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:387
#14 Twig_Template:displayWithErrorHandling in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:355
#13 Twig_Template:display in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Template.php:366
#12 Twig_Template:render in /vagrant/grav-admin/vendor/twig/twig/lib/Twig/Environment.php:347
#11 Twig_Environment:render in /vagrant/grav-admin/system/src/Grav/Common/Twig/Twig.php:341
#10 Grav\Common\Twig\Twig:processSite in /vagrant/grav-admin/system/src/Grav/Common/Service/OutputServiceProvider.php:12
#9 Grav\Common\Service\OutputServiceProvider:Grav\Common\Service\{closure} in /vagrant/grav-admin/vendor/pimple/pimple/src/Pimple/Container.php:113
#8 Pimple\Container:offsetGet in /vagrant/grav-admin/system/src/Grav/Common/Grav.php:10
#7 Grav\Common\Processors\RenderProcessor:process in /vagrant/grav-admin/system/src/Grav/Common/Grav.php:123
#6 Grav\Common\Grav:Grav\Common\{closure} in /vagrant/grav-admin/system/src/Grav/Common/Grav.php:385
#5 Grav\Common\Grav:Grav\Common\{closure} in /vagrant/grav-admin/system/src/Grav/Common/Grav.php:361
#4 call_user_func_array in /vagrant/grav-admin/system/src/Grav/Common/Grav.php:361
#3 Grav\Common\Grav:__call in /vagrant/grav-admin/system/src/Grav/Common/Grav.php:124
#2 Grav\Common\Grav:measureTime in /vagrant/grav-admin/system/src/Grav/Common/Grav.php:124
#1 Grav\Common\Grav:process in /vagrant/grav-admin/index.php:38
#0 {main} in /vagrant/grav-admin/index.php:0
```

```yml
title: Groups
'@extends': default

form:
    fields:
        tabs:
            type: tabs

            fields:
                group:
                    type: tab
                    title: Groups

                    fields:
                        header.groups:
                            name: groups
                            type: list
                            label: Groups

                            fields:
                                .wrappers:
                                    name: wrappers
                                    type: list
                                    label: Wrappers

                                    fields:
                                        .height:
                                            type: select
                                            size: long
                                            label: Height
                                            options:
                                                full: Full
                                                half: Half
                                        .images:
                                            name: images
                                            type: list
                                            style: vertical
                                            label: Images

                                            fields:
                                                .image:
                                                    type: pagemediaselect
                                                    label: Image
                                                .width:
                                                    type: select
                                                    size: long
                                                    label: Width
                                                    options:
                                                        full: Full
                                                        half: Half
```
