### ISSUE TITLE
description attribute is not translated in blueprint 

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav-plugin-admin#729]
I notice that `description` attribute is not translated
````
                header.seotwitterimg:
                  type: pagemediaselect
                  label: MYTHEME_POST_FEATURED_IMAGE
                  help: MYTHEME_SEO_DEFAULT_IMG
                  description: MYTHEME_SEO_DEFAULT_IMG
````
