### ISSUE TITLE
Getting "unresponsive script" errors in Firefox

### ISSUE THREAD

**Issue by fredrikekelund** [getgrav/grav-plugin-admin#736]
In Firefox 48 on macOS with Grav v1.1.3 and Admin v1.1.4, every time I reload the admin plugin's view of a particular page on my site, I get an "unresponsive script" error. I can simply click "continue", and things then work as expected, but the browser does freeze for a few seconds just after loading the page. Firefox complains that it's the jQuery script that's causing the error, so I guess some library call is somehow freezing the browser.

I suspect that the problem comes from me having a long (and nested) list control for this page.

Here's the blueprint:

``` yml
title: Groups
'@extends': default

form:
  fields:
    tabs:
      type: tabs

      fields:
        group:
          type: tab
          title: Groups

          fields:
            header.groups:
              name: groups
              type: list
              btnLabel: "Add group"
              style: vertical
              label: Groups

              fields:
                .project:
                  name: project
                  type: pages
                  label: Project
                  show_all: false
                  show_modular: false
                  show_root: false

                .media:
                  name: media
                  type: list
                  btnLabel: "Add media"
                  style: vertical
                  label: Media

                  fields:
                    .media:
                      type: pagemediaselect
                      classes: fancy
                      label: Media
                    .width:
                      type: select
                      classes: fancy
                      size: long
                      label: Width
                      options:
                        half: Half
                        quarter: Quarter

```

And here's the content of my page (image and project names have been obfuscated). There's 52 groups in there and each contains 1-6 images (71 in total).

``` yml
title: Home
menu: Start
groups:
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: quarter
            -
                media: example.jpg
                width: quarter
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
            -
                media: example.jpg
                width: quarter
            -
                media: example.jpg
                width: quarter
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                width: half
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: quarter
            -
                media: example.jpg
                width: quarter
    -
        project: example
        media:
            -
                width: quarter
            -
                media: example.jpg
                width: quarter
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: quarter
            -
                media: example.jpg
                width: quarter
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: quarter
            -
                media: example.jpg
                width: quarter
            -
                media: example.jpg
                width: quarter
            -
                media: example.jpg
                width: quarter
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
            -
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: quarter
            -
                width: quarter
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
            -
                media: swim2.mp4
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
            -
                media: example.jpg
                width: half
            -
                media: example.jpg
                width: quarter
            -
                media: example.jpg
                width: quarter
            -
                media: example.jpg
                width: quarter
            -
                width: quarter
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                width: half
            -
                media: example.jpg
                width: quarter
            -
                media: example.jpg
                width: quarter
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: quarter
            -
                media: example.jpg
                width: quarter
            -
                width: quarter
    -
        project: example
        media:
            -
                media: example.jpg
                width: quarter
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
            -
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: quarter
    -
        project: example
        media:
            -
                media: example.jpg
                width: quarter
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: quarter
            -
                media: example.jpg
                width: quarter
    -
        project: example
        media:
            -
                width: half
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: quarter
    -
        project: example
        media:
            -
                media: example.jpg
                width: quarter
            -
                width: quarter
            -
                width: quarter
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: half
    -
        project: example
        media:
            -
                media: example.jpg
                width: quarter
    -
        project: example
        media:
            -
                media: example.jpg
                width: quarter
```

**Comment by fredrikekelund** [comment]
Firefox seems to have changed the way they warn about this in v50 (I tested in Firefox developer edition), so the user doesn't get a blocking pop-up, but the page is still very slow to render and makes the browser unresponsive for a couple of seconds.

**Comment by w00fz** [comment]
Unfortunately this is caused by the Selectize which has always been quite inefficient.
Assuming you have 52 groups with 6 images each, that is 1 selectize for the project + (6 * 2) selectize for media + width => 13 selectize per group, for 52 groups is 676. The fact that selectize is that inefficient is what causes the page to take a bit to load and I can see this causing issues.
Firefox seems fine to me however, it does take about the same as Chrome.

One workaround which is not really solving the issue but at least gives the browser a little more breath, is to make the width a toggle rather than selectize.

```yaml
  .width:
    type: toggle
    label: Width
    classes: fancy
    highlight: half
    options:
        'half': Half
        'quarter': Quarter
```

This will remove 1 for each image for a total of now 364 selectize which is almost half of before.


One thing this issue brought to my attention, is that we do not have a way to disable selectize from certain select. the `pages` field shouldn't be relying on selectize and work with regular native select fields.

I'm going to take a look at improving this.
