### ISSUE TITLE
Changes inside custom fields not being saved

### ISSUE THREAD

**Issue by jeremyblaze** [getgrav/grav-plugin-admin#737]
This is my first Grav site. I'm building a (pretty simple) custom site for a client and I'm having trouble setting up the custom fields. Fields are appearing fine in the admin interface, but when I enter some text and hit save the changes are lost – despite getting the ‘Successfully Saved’ message.

Any help would be much appreciated.

This is happening on all blueprints with custom fields. The stock fields work fine.

**Example blueprint**
```
title: Home
'@extends':
    type: default
    context: blueprints://pages
    
form:
    fields:
        col1-heading:
            type: text
            label: Heading
        col1-content:
            type: editor 
            
        col2-gravH:
            type: section
            title: Column 2
            underline: true
        col2-heading:
            type: text
            label: Heading
        col2-content:
            type: editor
            
        col3-gravH:
            type: section
            title: Column 3
            underline: true
        col3-heading:
            type: text
            label: Heading
        col3-content:
            type: editor
```

(also asked this on the forum: https://getgrav.org/forum#!/general:changes-inside-custom-field)

**Comment by jeremyblaze** [comment]
Alright so solved this myself - I was being a numbskull and not prefixing the field names with `header.` e.g.

```
fields:
   header.col1gravH:
      type: section
      title: Column 1
      underline: true
```
