### ISSUE TITLE
Taxonomy diacritics

### ISSUE THREAD

**Issue by iskrisis** [getgrav/grav-plugin-admin#738]
Taxonomies in nonenglish languages without being able to use accented characters are not realy useful.

For example czech:
exhibition - výstava
food - jídlo
important - důležitý

Its seems that the admin now does not allow use of these accented characters for taxonomy field. Is there some kind of validation going on maybe?

**Comment by flaviocopes** [comment]
Just tested, I don't see any problem - tested saving

![screen shot 2016-08-22 at 12 15 24](https://cloud.githubusercontent.com/assets/11783388/17851367/eb6fa53e-6861-11e6-9ebd-ecc27ab25a49.png)

Was saved as

```
taxonomy:
    category:
        - blog
        - důležitý
    tag:
        - důležitý
```
