### ISSUE TITLE
Users without "super: true" admin login redirecting loop

### ISSUE THREAD

**Issue by bgambier** [getgrav/grav-plugin-admin#739]
(Grav v1.1.3 - Admin v1.1.4 - Login v2.0.1)
Hello,

Since I've updated grav & plugins in latest versions, users with this config can't access to the admin:
```
access:
  admin:
    login: true
    pages: true
  site:
    login: true
```

After the login form, admin scripts seem to loop redirecting to the Dashboard page, with this error:

![grav-logged-out-problem](https://cloud.githubusercontent.com/assets/11303103/17779054/9bfcf3e2-6566-11e6-8b10-42f04c9ecf1c.jpg)

If I add `super: true` everything works, but I don't want them to access to the website configuration...

Any idea ?

Thx
