### ISSUE TITLE
Filepicker inside list: Impossible to select images on creation.

### ISSUE THREAD

**Issue by nepomuk13** [getgrav/grav-plugin-admin#773]
When a filepicker is inside a list element, creating a new element create the field, but the dropdown does not work, and saving just delete the empty element.

```
            header.mysponsors:
              type: list
              fields:
                .logo:
                  type: filepicker
                  preview_images: true
```
