### ISSUE TITLE
Wrong duplication records with file type field

### ISSUE THREAD

**Issue by aaromnido** [getgrav/grav-plugin-admin#775]
Hi there,
I just find the next issue:

I have thi blueprint :

```yaml
title: Bandos
@extends:
    type: default
    context: blueprints://pages

form:

    fields:

        tabs:

            fields:

                documentos:
                    type: tab
                    title: Bandos
                    fields:

                        header.documentos:
                            name: documentos
                            type: list
                            label: Bandos
                            fields:

                                .title:
                                    type: text
                                    label: Título
                                    validate:
                                        required: true
                                        type: text

                                .date:
                                    type: date
                                    label: Fecha
                                    validate:
                                        required: true
                                        type: date

                                .file:
                                    type: file
                                    label: Documento
                                    destination: 'user/pages/06.el-ayuntamiento/03.bandos/documentos'
                                    multiple: false
                                    filesize: 5
                                    avoid_overwriting: true
                                    limit: 1
                                    accept:
                                        - .pdf
```

But when I try to create an item (item list) on the admin panel, it duplicates the record in a strange way. Then I get an .md like this. One without file data and another one with file data:

![captura de pantalla 2016-09-14 a las 12 39 12](https://cloud.githubusercontent.com/assets/640649/18509344/5c40a484-7a78-11e6-9725-0296db1ca3b5.png)

Can you check out this?

Thanks a lot!
