### ISSUE TITLE
Notification setting not always working 

### ISSUE THREAD

**Issue by maxfrigge** [getgrav/grav-plugin-admin#818]
I have disabled all notifications:

```yaml
notifications:
  feed: false
  dashboard: false
  plugins: false
  themes: false
```

However the admin still shows the "Vote for Grav..." notification.
