### ISSUE TITLE
Infinite recursion when using the "file" field type inside a page blueprint

### ISSUE THREAD

**Issue by parcand** [getgrav/grav-plugin-admin#820]
Using the "file" field type inside a page blueprint seems to break the Twig compilation sequence. 

The following error shows up:
`Maximum function nesting level of '100' reached, aborting!`

Example:

/site/user/themes/mytheme/blueprints/book.yaml

```
title: Book

'@extends':
  type: default
  context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab
          unset@: true
        book:
          type: tab
          title: Book
          ordering@: -2

          fields:
            header.cover:
              type: file
              label: Cover
              accept:
                - image/*
```
