### ISSUE TITLE
Form and multi-language in modular page

### ISSUE THREAD

**Issue by ekiwnox** [getgrav/grav-plugin-admin#821]
Hi guys,

I have a problem with a form in a module for a modular page. I needed a special form, so I decided to create it with blueprint. It works quite nice without the multi-language, but when I save the filled form in a specific language, the default form appears and the content of my own form is deleted...

The form perfectly works if I don't select a specific language... but I really need it in two languages. 

Here's a link with the video of the issue : 
https://youtu.be/bOd2xs0RShs

Hope I'm clear ! Sorry for my english (I'm not a native speaker)

Here's the code of my form : 
```
title: columns-module
form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        gallery:
          type: tab
          title: Worker
          fields:
           header.worker:
              name: Worker
              type: list
              style: vertical
              label: Add a new worker
              fields:
                .name:
                  type: text
                  label: name
                .history:
                  type: text
                  label: history
```
