### ISSUE TITLE
issue when delete a file (accented name or space)  uploaded via blueprint file

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav-plugin-admin#833]
when upload a file with accented characters or space and delete it within theme config, the file is deleted (normal behavior) but in the theme config it not deleted this instead : `el_favicon_single: {  }`
and if you save your theme config again this happen 
![capture d ecran 2016-10-21 a 13 37 11](https://cloud.githubusercontent.com/assets/3842190/19597219/8b5f48c8-9793-11e6-9046-d30e66e1a8f6.png)

404 because the file was deleted, but in the theme config the path remains
Hope you can reproduce it
my blueprint :
````
            el_favicon_single:
              type: file
              label: ''
              multiple: true
              destination: 'user/themes/MYTHEME/images/'
              showuploaded: true
              showuploadedpreview: true
              accept:
                  - image/*
````

tested with same image but remove accented in the file name everything was ok

Thanks

**Comment by flaviocopes** [comment]
Interesting, I replicated it using a page blueprint.

Uploaded a file and it's saved as 

```
el_favicon_single:
    user/ààààà.png:
        name: ààààà.png
        type: image/png
        size: 33585
        path: user/ààààà.png
```

which is correct, but while the file is removed from the filesystem, it's never deleted from the page header.
