### ISSUE TITLE
List with sections in page blueprints

### ISSUE THREAD

**Issue by DavideTrendstudio** [getgrav/grav-plugin-admin#837]
Hi!
I am developing an admin form (page blueprint) in which I need to insert a list divided in subsections (with type: section). Everything is working fine, except the filepicker field: when i put this field inside a section of the list, the selector is not displaying a list of the images inside the referenced folder, instead it only shows a list of the files present in the page's folder, e.g.: example.en.md, example.it.md, example.de.md ....

Not really sure if this is an issue or I am using the incorrect syntax.
I tried the following code:

1)

```
header.list:
    type: list
    label: example
    fields:
        section1:
            type: section
            title: section1
            fields:
                .image:
                     type: filepicker
                     folder: 'user/images'
```

and:

2)

```
header.list:
    type: list
    label: example
    fields:
        section1:
            type: section
            title: section1
       .image:
            type: filepicker
            folder: 'user/images'
```

Everything is working fine with both versions, except the filepicker field
Any idea why is this happening?

**Comment by flaviocopes** [comment]
Replicated, when inside a list the field gets from the page's files instead of from the specified `folder`.

**Comment by flaviocopes** [comment]
The issue is with the `section` field. Your example 2) works if you prepend the dot to section1, making it
```

            header.list2:
              type: list
              label: example
              fields:
                .section1:
                  type: section
                  title: section1
                .image:
                  type: filepicker
                  folder: 'user/images'
```
