### ISSUE TITLE
PageMediaSelect not working

### ISSUE THREAD

**Issue by jgog** [getgrav/grav-plugin-admin#845]
Hey!

I am using the `PageMediaSelect` to pick uploaded media for a pages admin form. But it doesn't work anymore (used to work previously). Here is a my blueprint:

```
  header.downloads:
                type: list
                label: Downloads
                fields:
                  .type:
                    type: selectize
                    label: Type of Insurance
                  .company:
                    type: selectize
                    label: Company
                  .form1:
                    type: pagemediaselect
                    label: Proposal Form
                    destination: 'user/data/downloads'
                    blueprint: 'themes.themename'
                    accept:
                      - application/pdf
```
