### ISSUE TITLE
@Blueprints: Add file upload > filesize: 0 > not working

### ISSUE THREAD

**Issue by ponderboy** [getgrav/grav-plugin-admin#855]
I have the maximum filesize within the settings set to 0. Within a page blueprint I added a file upload and there also set the filesize to zero (which should be unlimited, shouldn't it?). When dragging in a picture I get: 

> File is too big (0.07MiB). Max filesize: 0MiB.

**Comment by flaviocopes** [comment]
No, 0 does not mean unlimited in DropzoneJS which is the lib we use for the file uploader http://www.dropzonejs.com/#config-maxFilesize

There seem to be no value for "unlimited"

**Comment by ponderboy** [comment]
Strange. I'm pretty sure I used it before and it worked. (Prior the last update) Also in the documentation it says: 

> When set to 0, it is considered unlimited, ...

[https://learn.getgrav.org/forms/blueprints/how-to-add-file-upload](https://learn.getgrav.org/forms/blueprints/how-to-add-file-upload)

Well then, good to know. Thanks.

**Comment by flaviocopes** [comment]
I didn't check that, it might be as well be unlimited, and you're having a different issue. Going to check if I can replicate.

**Comment by w00fz** [comment]
You cut off the other portion of the docs :)

> When set to 0, it is considered unlimited, however it is constraint to your Grav system.media.upload_limit as well as your PHP setting

**Comment by ponderboy** [comment]
Because, it is the important part within my issue. System and PHP Settings are adjusted as I wrote (though not so clearly):

> I have the maximum filesize within the settings set to 0 ....

And it says in the docs: 
[https://learn.getgrav.org/admin-panel/configuration-system#media](https://learn.getgrav.org/admin-panel/configuration-system#media)

;)

**Comment by flaviocopes** [comment]
Disregard my previous comment - `limit: 0` works fine to me, it's unlimited and I can upload any file size in my testing.

**Comment by ponderboy** [comment]
I've just tried out a blank install of grav cms, due to some other error I got, and there those issues don't come up. So I think this thread can be closed... 
Thank you guys.

**Comment by w00fz** [comment]
Feel free to reopen if this happens again.

**Comment by ponderboy** [comment]
Well, the problem occurs again: 
`File is too big (0.11MiB). Max filesize: 0MiB.`

However I don't get the error if I drag files in the default uploads field of the page.  

> 
    # works  
            uploads:
              label: Default Upload
    # doesn't work
            header.file:
              title: File
              type: file
              label: File Upload
              style: vertical
              multiple: false
              destination: 'self@'
              random_name: false
              avoid_overwriting: false
              limit: 1
              filesize: 0
              accept:
                - image/*

**Comment by anthubbard** [comment]
I have this same problem. This is my config:
```
header.downloads:
    name: downloads
    type: list
    style: vertical
    label: Page Downloads
    fields:
      .text:
        type: text
        label: Download Button Text
        style: vertical
      .dl:
        type: file
        label: Add a file
        accept: ["image/*", '.doc', '.docx', '.xls', '.xlsx', '.pdf']
        style: vertical
        destination: '@self'
        multiple: false
        limit: 1 
        filesize: 50
```
Won't let me upload anything over about 1.5mb - I can upload some files but there is a limit somewhere - I just didn't find the exact limit.

**Comment by flaviocopes** [comment]
@anthubbard I tried that snippet and it works fine to me with a 9MB file. Check the PHP limits and Grav system's "File upload limit" setting.

**Comment by anthubbard** [comment]
Hey @flaviocopes Where is the Grav System file upload limit setting? That's probably my issue... thanks

**Comment by w00fz** [comment]
Configuration -> System -> Media -> File upload limit

**Comment by anthubbard** [comment]
Hmm, no its set to:
```
media:
  upload_limit: 0
```
PHP upload limit definitely isn't the problem, I have a lot of sites on the same server that regularly upload 50mb +

**Comment by w00fz** [comment]
Can you try setting it to 50000000?

**Comment by anthubbard** [comment]
Nope, still same issue after making it 500000000

**Comment by anthubbard** [comment]
I fixed this issue for me, was a blueprint config problem, sorry for the fuss ;)

**Comment by ponderboy** [comment]
Hey anthubbard,
what exactly was the blueprint config problem? As I have the same problems and would like to know, how you made it work.

**Comment by anthubbard** [comment]
Hey Ponderboy, tbh it was pretty stupid - I had a blueprint overriding another one and I didn't realise and I just had the limit and filesize switched:
```
header.newsletter:
  type: file
  destination: '@self'
  multiple: false
  limit: 100
  filesize: 1
  accept: ["image/*", '.doc', '.docx', '.xls', '.xlsx', '.pdf']
```
So, limit was supposed to be 1 and filesize 100, but I wasn't looking at this blueprint. Why don't you post a snippet of your blueprint in the forum so we can have a look?
```
