### ISSUE TITLE
listfield with columns > on save disapears

### ISSUE THREAD

**Issue by ponderboy** [getgrav/grav-plugin-admin#867]
Well I have a list field with coulumns. After adding an item and filling out the fields, once I hit save, the item disapeared.
```
header.auszeichnungen:
          name: auszeichnungen
          type: list
          toggleable: true
          collapsed: true
          style: vertical
          label: Auszeichnungen und Preise
          btnLabel: Auszeichnung Hinzufügen
          fields:
            .columns:
              type: columns
              fields:
                column1:
                  type: column
                  fields:
                    .icon:
                      type: toggle
                      label: Icon (Pokal für Preise, Badge für Auszeichnungen)
                      highlight: 1
                      options:
                          1: Pokal
                          0: Badge
                      validate:
                          type: bool

                column2:
                  type: column
                  fields:
                    .platz:
                      type: text
                      label: Platz / Kategorie
                      placeholder: 'z.B: 1. Preis oder Finalist'

                column3:
                  type: column
                  fields:
                    .title:
                      type: text
                      label: Name
                      placeholder: 'z.B: Hörspielpreis 2016'
```
