### ISSUE TITLE
images in preview for previous uploaded files are skewed and fixed

### ISSUE THREAD

**Issue by erichgoldman** [getgrav/grav-plugin-admin#888]
The SCSS has set fixed [width and height](https://github.com/getgrav/grav-plugin-admin/blob/4da49c487dd9d36015b19902b36ffb49e58f10e4/themes/grav/scss/template/_dropzone.scss#L3):

```scss
$preview-width: 150px;
$preview-height: 100px;
```
However, this is used for the [image itself](https://github.com/getgrav/grav-plugin-admin/blob/4da49c487dd9d36015b19902b36ffb49e58f10e4/themes/grav/scss/template/_dropzone.scss#L192):

```SCSS
        .dz-details {
            width: $preview-width;
            height: $preview-height;

           ...

            img {
                position: absolute;
                top: 0;
                left: 0;
                width: $preview-width;
                height: $preview-height;
            }

            ...
        }
```

This results in an image being skewed to fix dimensions without regard for the original image. Instead, I would expect that the image would fit the container rather than stretching - e.g.,  set a max size, center in the box using ratios inline with the original image.

Is there particular reason this is fixed width?

Given this image:

![image](https://cloud.githubusercontent.com/assets/3157148/20911411/c017bcc4-bb35-11e6-8089-a2c0b6163512.png)

it display like this in the Admin:

![image](https://cloud.githubusercontent.com/assets/3157148/20911421/ced5e1d2-bb35-11e6-8fc7-b1762ad10433.png)

It does not do this skewing in the preview after upload and before saving.

Rendered CSS:

```css
.dropzone .dz-preview .dz-details img {
    position: absolute;
    top: 0;
    left: 0;
    width: 150px;
    height: 100px;
}
```
