### ISSUE TITLE
File Field upload error

### ISSUE THREAD

**Issue by frabenanti** [getgrav/grav-plugin-admin#930]
Hi,
i'm trying to extend modular pages with a custom field via blueprints, this is my code:

---------------------------------------------------------------------------------------------------

```
title: Brands
@extends:
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        gallery:
          type: tab
          title: Brands

          fields:
            header.brands:
              type: file
              label: Add a brand
              multiple: true
              limit: 5
              accept: - image/*
```

---------------------------------------------------------------------------------------------------

Everything works fine but when i'm trying to save the image previously uploaded via the input file, Grav doesn't show any attachment...

NB: my default.yaml is in themes/my-theme/blueprints/modular/ folder

**Comment by flaviocopes** [comment]
Indentation matters.

```
              accept: - image/*
```

is confusing the image processing, and I got the problem too. 
Also, add a destination path.

Use:

```yaml

            header.brands:
              type: file
              destination: 'self@'
              label: Add a brand
              multiple: true
              limit: 5
              accept: 
                - image/*
```

instead, it will work.
