### ISSUE TITLE
(SUG|REQ) Admin-Plugin Modifications...

### ISSUE THREAD

**Issue by LagSwitchedVirginity** [getgrav/grav-plugin-admin#937]
# (SUG|REQ) Admin-Plugin Modifications...

```text
I would like it if you would make it possible, since I don't see it in the API or anywhere as such!
It would add to the tabs on the side with fluid like action!
And it would also be basically interactive for the users needs!
I would like to add an admin control panel for some servers I host!!
And I would like it on the users page!
I would make the plugin to add the functionality, but I would like to not have to modify the .twig every other minute.
```

---

EX:
```yaml
Title: <tabname>
AdminPG: <filename>
AdminLVL: {0(default),1(super)}
```
