### ISSUE TITLE
Can't edit user's info in Admin Panel

### ISSUE THREAD

**Issue by jasiekkaminski** [getgrav/grav-plugin-admin#943]
When I'm logged as a user with
```
access:
  admin:
    login: true
    pages: true
  site:
    login: true
```

I'm trying to change my e-mail and language, but it's impossible. When I click "Save" button the message is displayed:

> You have insufficient permissions for task save.
