### ISSUE TITLE
Bug: Toggleable fields with default values are always set to page header

### ISSUE THREAD

**Issue by Sommerregen** [getgrav/grav-plugin-admin#961]
My **External Links** plugin have had a strange bug. Even no plugin specific page header value was selected, there were always some options set after hitting "save" in the Admin plugin. To reproduce the issue, consider the page blueprint

```yaml
form:
  validation: loose

  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        options:
          type: tab

          fields:
            my_plugin:
              type: section
              title: "My plugin"
              underline: true

              fields:
                header.my_plugin.optional_toggle:
                  type: toggle
                  toggleable: true
                  label: "Optional toggle"
                  highlight: 1
                  default: 1
                  options:
                    1: PLUGIN_ADMIN.YES
                    0: PLUGIN_ADMIN.NO
                  validate:
                    type: bool
```

Although the field is toggleable (and unselected in the first place) it will always be written to the page header after hitting save. On the other hand leaving out `default: 1` works as expected.
