### ISSUE TITLE
Strange translation problem

### ISSUE THREAD

**Issue by leotiger** [getgrav/grav-plugin-admin#963]
I have several blueprints defined for a website including a default.yaml and an expo.yaml.

The expo.yaml does not inherit default.yaml but both include a definition for a select form field with the same name but with a slightly different set of options.

When I try to save a page based on expo.yaml in a different language with a select value that is not included in the option set in default.yaml with the same name I receive an error as response indicating that validation failed. The translation .md file is saved with 0 bytes.

If I include the options existing in expo.yaml to the select in default.yaml than I can save the translation without problems.

This indicates to me that the default.yaml plays a roll (I haven't looked into the code) despite the fact that expo.yaml is defined as a complete blueprint without inheritance. Could you look into this?

u

**Comment by flaviocopes** [comment]
Can you provide those two blueprints, to easily replicate the problem?

**Comment by leotiger** [comment]
Sure, but you won't be able to use them easily as there are a lot of references to private plugins I coded that substitute the whole editing stack of GRAV.

To help you a bit I place here code reference of the important part:

in expo.yaml we have
```
                    header.fullwidth:
                      type: select
                      size: long
                      label: Page Style
                      name: fullwidth
                      help: Select a page style
                      default: row
                      options:
                        row: Row (Max width: 1008px)
                        rowfull: Row full (with Grid)
                        rowfullfull: Row (without Grid)
```
and in defaut.yaml quite the same:
```
                    header.fullwidth:
                      type: select
                      size: long
                      label: Page Style
                      name: fullwidth
                      help: Select a page style
                      default: row
                      options:
                        row: Row (Max width: 1008px)
                        rowfull: Row full (with Grid)
```
There's only one difference between the two definition: rowfullfull is missing in default.yaml. If a page with template expo.yaml is configured to present itself with rowfullfull translation fails. If it's configured with row or rowfull present in both .yamls I encounter no problem.

I prepare a zip with the two blueprints.

Regards.
u
