### ISSUE TITLE
Unable to edit/remove list items when trying to add global options with default.yaml 

### ISSUE THREAD

**Issue by JLehtinen** [getgrav/grav-plugin-admin#969]
Cannot remove or edit list items in the admin. Adding works fine.

To replicate: add a global option on the Admin tool's Pages/Options tab with file `/themes/mytheme/blueprints/default.yaml` using this content:

```
title: Default
extends@:
  - type: default

form:
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        options:
          fields:
            header:
              type: section
              title: Header
              underline: true
              fields:
                header.nav_hidden:
                  type: toggle
                  label: Hide navigation
                  highlight: 0
                  default: 0
                  options:
                    1: 'Yes'
                    0: 'No'
                  validate:
                    type: bool
                header.header_transparent:
                  type: toggle
                  label: Transparent header
                  highlight: 0
                  default: 0
                  options:
                    1: 'Yes'
                    0: 'No'
                  validate:
                    type: bool
                header.nav_bright:
                  type: toggle
                  label: White logo and links
                  highlight: 0
                  default: 0
                  options:
                    1: 'Yes'
                    0: 'No'
                  validate:
                    type: bool
```

If you remove the above file editing/deleting list items works fine.
