### ISSUE TITLE
css issue with Editor field and codemirror

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav-plugin-admin#971]
Since last update i have a issue with editor and codemirror. see gif
It appears only on page blueprint, in my theme blueprint i have the same editor field and no issue

NB: In fullscreen mode it's ok

![ezgif com-9818f8a54c](https://cloud.githubusercontent.com/assets/3842190/22862391/d35f99a4-f12d-11e6-9839-73138a78115f.gif)

````
                header.css:
                  classes: frontmatter
                  type: editor
                  label: THEME_CSS
                  autofocus: true
                  codemirror:
                    mode: 'css'
                    indentUnit: 4
                    autofocus: true
                    indentWithTabs: false
                    lineNumbers: true
                    styleActiveLine: true
                    gutters: ['CodeMirror-lint-markers']
                    lint: true
````
