### ISSUE TITLE
Configure Media Manager folder

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-plugin-admin#998]
I need an option to configure path of Media Manager:
![image](https://cloud.githubusercontent.com/assets/7556290/23287524/17196400-fa92-11e6-9760-1cc3a084b73b.png)

By default it's root folder, but for example, I want to specify `root\images` folder with blueprints for my blog posts.
I can't find needed `folder` option for this type of field in documentation:
https://learn.getgrav.org/forms/blueprints/fields-available#the-pagemediaselect-field

It is only available for File field:
https://learn.getgrav.org/forms/blueprints/fields-available#the-file-field

**Comment by Sogl** [comment]
I did some testing and found that Filepicker field isn't suitable for viewing already uploaded files. Only Media Manager can handle them:
![image](https://cloud.githubusercontent.com/assets/7556290/23289996/c46c36be-faa1-11e6-9266-c2eea24d2647.png)

My blueprint conf:
```yaml
title: Gallery
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          fields:
            custom_file:
              type: file
              label: A Label
              multiple: false
              destination: 'self@'
              random_name: false
              avoid_overwriting: true
              limit: 10
              filesize: 5
              accept:
                - image/*
```
